/**
 * io Python↔TS 동작 일치 회귀 테스트.
 *
 * 모든 기대값은 Python 원본(src/python/ko_pii/io_, CPython 3.12.14)을 같은 픽스처에 실제로
 * 실행해 얻은 출력이다. zip/xml 픽스처는 Python zipfile 로 만든 바이트를 base64 로 박아
 * 두었다 (EOCD 엔트리 수·선언 크기·로컬 헤더 이름 등은 바이트 패치로 조작한 것).
 * 이 파일은 생성물이 아니라 손으로 고쳐도 되지만, 기대값을 바꿀 때는 반드시 Python 실측으로.
 */
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { BoundedReadError, FileReadPolicy, readTextBounded } from "../../src/io/bounded.js";
import { CsvError, readRecordsFromText } from "../../src/io/csvReader.js";
import { readRecords as dispatchReadRecords, extensionOf } from "../../src/io/dispatcher.js";
import { readText as readDocx } from "../../src/io/docx.js";
import * as ioIndex from "../../src/io/index.js";
import { normalizeForDetection } from "../../src/io/textNormalizer.js";
import { readText as readXlsx, readRecords as readXlsxRecords } from "../../src/io/xlsx.js";

const DIR = mkdtempSync(join(tmpdir(), "ko-pii-io-parity-"));

function fixture(name: string, base64: string): string {
  const path = join(DIR, name);
  writeFileSync(path, Buffer.from(base64, "base64"));
  return path;
}

type BoundedExpectation = string | { text: string; members: number; decl: number };

async function boundedOutcome(path: string, policy?: FileReadPolicy): Promise<BoundedExpectation> {
  try {
    const doc = await readTextBounded(path, policy ?? null);
    return { text: doc.text, members: doc.archiveMembers, decl: doc.declaredDecompressedBytes };
  } catch (e) {
    if (e instanceof BoundedReadError) return `REJECT:${e.code}`;
    throw e;
  }
}

describe("xmlEt — ElementTree(expat) 의미론", () => {
  const cases: Array<[file: string, base64: string, pythonText: string]> = [
    [
      "d_space.docx",
      "UEsDBBQAAAAIAEaqMl0O43IHzgAAADYBAAARAAAAd29yZC9kb2N1bWVudC54bWyFj01OAzEMha8SZT91pkCpRjPprieAA4TEtCNNfmSHTnsIxLo36ZlA3IGkEkJISGyeZfn583O/OfpJHJB4jGGQ7UJJgcFGN4bdIB8fts1aCs4mODPFgIM8IcuN7ufORfviMWRRAIG7eZD7nFMHwHaP3vAiJgxl9hzJm1xa2sEcySWKFpkL30+wVGoF3oxBVuRTdKdaUxWqcqV3nIwtpxMhIx1Q6s/z6/vl8vF27qF4dFX6b0f86dWqVU27vLlt7lb3618WuAaB71jw87L+AlBLAQIUAxQAAAAIAEaqMl0O43IHzgAAADYBAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAAD9AAAAAAA=",
      "\n홍길동 010-1234-5678\n",
    ],
    [
      "d_cdata.docx",
      "UEsDBBQAAAAIAEaqMl3hmB/gugAAAAcBAAARAAAAd29yZC9kb2N1bWVudC54bWxVj8sKwjAQRX8lZuFOp7oQqWlFFL9AV+IiJrEWmpmQRGv9elPxgZs7DPdwhhHLu23YzfhQExZ8Ms44M6hI11gVfL/bjuachShRy4bQFLwzgS9L0eaa1NUajCwJMORtwS8xuhwgqIuxMozJGUzdmbyVMa2+gpa8dp6UCSH5bQPTLJuBlTXyXnki3fXT9eH7iKUYHNab1W51kOLEhtK6BVPHYyngVcKbe8P3L806lqjHHwYvM3zuwO+H8glQSwECFAMUAAAACABGqjJd4Zgf4LoAAAAHAQAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAA6QAAAAAA",
      "\na<b &amp; cx y z\n",
    ],
    [
      "d_utf16.docx",
      "UEsDBBQAAAAIAEaqMl2Lz0GtywAAAIABAAARAAAAd29yZC9kb2N1bWVudC54bWxtUEsOgjAUnIUHIeyl6MIFQdh5Aj2ACoqJQFPq74DGrTHxHp5AnRZsWJguOu/NzHvTft4xUpxRYg8PR+RQaLBDjQpT+BghQMjbI1NhzX5GtsLWsgvMMcOQqgmrFAlinBBRU1N74FTj0nS3GyrOjqgw3oJ9Dcla8DTUF1SXWBIH9EvrbX0b1spyumMVEwhOMiijVtmNOdmmy2d8AmOmD5lOWLdhfJdyZV9zcbV0SDmkibzb63G/Dp7mlbHd2vZ/WPWw7OH+fPH3XxJ8AVBLAQIUAxQAAAAIAEaqMl2Lz0GtywAAAIABAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAAD6AAAAAAA=",
      "\n유티에프16\n",
    ],
    [
      "d_nons.docx",
      "UEsDBBQAAAAIAEaqMl1BBz1TpQAAAPYAAAARAAAAd29yZC9kb2N1bWVudC54bWxljk0OwiAQha9C2NupLoxpKO48gR4AYdQmZYYwaO3tRU3jwuX7yfee2T/jqB6YZWDq9bpptULyHAa69vp0PKx2WklxFNzIhL2eUfTemqkL7O8RqagKIOmmXt9KSR2A+BtGJw0npJpdOEdXqsxXmDiHlNmjSOXHETZtu4XoBtJv5JnDbM3/o7q3rFmTrCmWWJGLKMl5NFBd+Nhl4q/61WHBwu+yfQFQSwECFAMUAAAACABGqjJdQQc9U6UAAAD2AAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAA1AAAAAAA",
      "\n",
    ],
    [
      "d_wsonly.docx",
      "UEsDBBQAAAAIAEaqMl2sNiBPqgAAACgBAAARAAAAd29yZC9kb2N1bWVudC54bWx1j90KwjAMhe99itJ7l+mFyNgPKvgE+gC1rdtgTUpbnXt7W0FUmDfnkC/hJCmbhxnYXTvfE1Z8leWcaZSkemwrfj4dl1vOfBCoxECoKz5pz5u6HAtF8mY0BhYD0BdjxbsQbAHgZaeN8BlZjbF3JWdEiKVrYSSnrCOpvY/5ZoB1nm/AiB55iryQmpLbJC5JqHclJEvqvjCbx/t5vGB/5g8/GF6r4X0IfJ6sn1BLAQIUAxQAAAAIAEaqMl2sNiBPqgAAACgBAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAADZAAAAAAA=",
      "\nA B\n  C\n",
    ],
    [
      "d_comment.docx",
      "UEsDBBQAAAAIAEaqMl3Ch5eJrAAAAPwAAAARAAAAd29yZC9kb2N1bWVudC54bWxVjkkOwjAMRa8Ssk9dWCBUddhxAjhAmriD1NhVEii9PU0lBGy+5e+nJ5fNy03iiT6MTJU8ZrkUSIbtSH0l77erukgRoiarJyas5IpBNnW5FJbNwyFFsQkoFEslhxjnAiCYAZ0OGc9I261j73TcVt/Dwt7Ong2GsPndBKc8P4PTI8mkbNmuac4pfIpY69aUB6WEEUrVFrsSUpvS/1A7wjStifpDYNfBRw7fx+s3UEsBAhQDFAAAAAgARqoyXcKHl4msAAAA/AAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAANsAAAAAAA==",
      "\nabcdef\n",
    ],
    [
      "c_xmlspace_root.docx",
      "UEsDBBQAAAAIAHeqMl0hfYhSewAAAKMAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzsEOwiAMBuBXMTyAXTx4IIyn2MErArJFSknBoG/vOg9evvZPm6Zm6ED+hbH00xtzaXrMau29aoDm14iunanGss8exOj6HjnBIA6VycfWtpIww2WaroBuK0rO6OxKmtWTlDVD3yl8pFaBhW6X22JAGpEP6+FvGf5v2S9QSwECFAMUAAAACAB3qjJdIX2IUnsAAACjAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAqgAAAAAA",
      "\nTXT\n",
    ],
    [
      "c_attr_lt.docx",
      "UEsDBBQAAAAIAHeqMl30DTDReQAAAJ0AAAARAAAAd29yZC9kb2N1bWVudC54bWxFzj0OwyAMBeCrRBygjjp0QIRTZOhKgfxIMUbGFcntG9Ihy/ds+Q02VQfyX4xJuh23VHQd1CKSNUDxS0RXHpRjOm8TMTo5V56hEofM5GMpa5pxg2ffvwDdmlTnBrWbQ1lT9YfC0TI3uCF2fI8G2tDky3z5L8P9kP0BUEsBAhQDFAAAAAgAd6oyXfQNMNF5AAAAnQAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAAKgAAAAAAA==",
      "\n",
    ],
    [
      "c_ctrl_char.docx",
      "UEsDBBQAAAAIAHeqMl3Ouf/lcwAAAJUAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzjEOwjAMBVBxE9QD4IqBIQqR4CYhCW2lOrZso8DtacrA8r4t/8G+uUzphaXa8Y1rVdeuw2zGDkDTXDDqibjU7fYkwWjbKhM0ksxCqagudcIVzuN4AYxLHYJv7kH505M70rFwO9w99KEru7z7K8P/kfAFUEsBAhQDFAAAAAgAd6oyXc65/+VzAAAAlQAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAAKIAAAAAAA==",
      "\n",
    ],
    [
      "c_doctype_plain.docx",
      "UEsDBBQAAAAIAHeqMl2DaK2OjgAAALYAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzrESwiAMBuBXQR6gqQ4OHKWDOuvQQUcs2HJXCBfQ6ttb6uDyJbn8l4ts335iL0vJYWj4tqp5q+TmeD50t8uJGSVnYbB/ehsyW6IhibnhY85RAKR+tF6nCqMNy+6B5HVeRhpgRjKRsLcpuTD4CXZ1vQevXeDl5B3Np9RYoEJW3bWTUJoircbVXxj+j6gvUEsBAhQDFAAAAAgAd6oyXYNorY6OAAAAtgAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAAL0AAAAAAA==",
      "\nTXT\n",
    ],
    [
      "c_crlf.docx",
      "UEsDBBQAAAAIAHeqMl1b9EUEeAAAAJsAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzkEKwyAQBdB9IXcoOUAnTaELsd7Fqk0CjjOMBtvbJyaLbt7nMwx8XZUnt2JI5frFmLKqr34uhRVAdnNAm2/EIe23DwnasleZoJJ4FnIh5yVNGGEchiegXVJvdFVv8r+W3JBGMfHeXeLYxYeGVptyyIfnC/znmA1QSwECFAMUAAAACAB3qjJdW/RFBHgAAACbAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAApwAAAAAA",
      "\nl1\nl2\nl3\n",
    ],
    [
      "c_lead_ws.docx",
      "UEsDBBQAAAAIAHeqMl2Ap8a7eAAAAJkAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzjEOwyAMBdA9p0A5QBx16IBSTpGhKwWaRIoxMo5obx9Ihy7P/rJluVNqKtqTOzBEUR/cY9bl0a8iSQNktwa0eaAUYp29idFKjbxAIfaJyYWct7jgDrdxvAPaLfamnnyR/7aaGtwQMz/nCVrT5Mt0+VuG/yOmOwFQSwECFAMUAAAACAB3qjJdgKfGu3gAAACZAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAApwAAAAAA",
      "\nTXT\n",
    ],
  ];
  for (const [file, base64, pythonText] of cases) {
    it(`docx.readText === Python: ${file}`, async () => {
      expect(await readDocx(fixture(file, base64))).toBe(pythonText);
    });
  }

  it("xlsx sharedStrings 의 xml:space + Python int() 인덱스(전각·밑줄·부호) + strip 의 U+FEFF", async () => {
    const path = fixture(
      "x_int.xlsx",
      "UEsDBBQAAAAIAF2uMl1bepU8SwAAAE0AAAAPAAAAeGwvd29ya2Jvb2sueG1sDclRDkAwDADQq8gOoIsPH4K7FGWydV3aJhyfz5c3P6J5E8ndy6XaEpJ7mwBsT8RovTSq/5yijP5TL7CmhIclIucCQ4wjMN41wPoBUEsDBBQAAAAIAF2uMl3Ys9mIiQAAAEABAAAUAAAAeGwvc2hhcmVkU3RyaW5ncy54bWxl0E0OgkAMBeCrkDmAHVBRydC7TLAKCfOTaUOMp3dwY2KX7+trF3XM0rzCGnk0s0geAHiaKXg+pEyxTh6pBC81lidwLuTvPBNJWKGztofgl2jQ8YJO8E0lORB0sOev7ccHzn6i0dRtprKRwRSp+Ssid0qOSk5Kzkp6JRclVyU3Ja3V1P4I6uvwA1BLAwQUAAAACABdrjJdfMdbEakAAACDAQAAGAAAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbLMpzy/KLs5ITS1RqMjNySu2VcooKSmw0tcvTs5IzU0s1ssvSM0DyqTlF+UmlgC5Ren6xQVFqYkpYE25OfpGBgZm+rmJmXlKdjZgMZfEkkQ7m6L8cjubZIUSW6XikiKgVJldho1+mZ2NfjIQgyWRVIDl3++ZCFeBJGwYb4BNWEHbUAGbuK4hVkP0sBoSj1XxzcW4XQr1y/vd+wmqObQATYk+UvDow8PdDgBQSwECFAMUAAAACABdrjJdW3qVPEsAAABNAAAADwAAAAAAAAAAAAAAgAEAAAAAeGwvd29ya2Jvb2sueG1sUEsBAhQDFAAAAAgAXa4yXdiz2YiJAAAAQAEAABQAAAAAAAAAAAAAAIABeAAAAHhsL3NoYXJlZFN0cmluZ3MueG1sUEsBAhQDFAAAAAgAXa4yXXzHWxGpAAAAgwEAABgAAAAAAAAAAAAAAIABMwEAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbFBLBQYAAAAAAwADAMUAAAASAgAAAAA=",
    );
    expect(await readXlsx(path)).toBe("h\none \ts10\tone \ts11\t\t\ts3\n﻿\n \n\n");
    expect(await readXlsxRecords(path)).toEqual([{ h: "one " }, { h: "﻿" }]);
  });
});

describe("bounded — Python zipfile 과 같은 판정", () => {
  const cases: Array<[file: string, base64: string, python: BoundedExpectation]> = [
    [
      "z_count_lie.docx",
      "UEsDBBQAAAAIAEaqMl0TPcbemwAAANAAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjk0OwiAQha9C2FuqC2Oa/uw8gR6AlrElgRnCYGtvL9SFm+/lZTJfXjt8vBMrRLaEnTxXtRSAExmLcyefj/vpJgUnjUY7QujkDiyHvt0aQ9PbAyaRBcjN1sklpdAoxdMCXnNFATDfXhS9TrnGWW0UTYg0AXP2e6cudX1VXluURTmS2UuGgliQ+tWyHR20qpTCeDAc/D2o/5j+C1BLAwQUAAAACABGqjJdaV7tjKoAAADJAAAAEAAAAHdvcmQvaGVhZGVyMS54bWwdzl0LgjAUBuC/Mnefm1YiMieRA72xCG8iujBdKrgPNkl/fs6bB17OOS+HZKuYwI8bOyqZwsDHMKPEy2/X+nlnYAUv4rGqLusn4AB+lBKQvilZkqEzYDuVNllSOMyzThCy7cBFY32ludxmX2VEM2/R9GhRptNGtdzaUfZiQiHGERLNKKFr0w7jmGlR5jmrQMEuOXuAOMYBDg5BeDydo5ggt+E0u3p3+4X+AVBLAQIUAxQAAAAIAEaqMl0TPcbemwAAANAAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLAQIUAxQAAAAIAEaqMl1pXu2MqgAAAMkAAAAQAAAAAAAAAAAAAACAAcoAAAB3b3JkL2hlYWRlcjEueG1sUEsFBgAAAAABAAEAfQAAAKIBAAAAAA==",
      "REJECT:xml_dtd_rejected",
    ],
    [
      "z_count_zero.docx",
      "UEsDBBQAAAAIAEaqMl0TPcbemwAAANAAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjk0OwiAQha9C2FuqC2Oa/uw8gR6AlrElgRnCYGtvL9SFm+/lZTJfXjt8vBMrRLaEnTxXtRSAExmLcyefj/vpJgUnjUY7QujkDiyHvt0aQ9PbAyaRBcjN1sklpdAoxdMCXnNFATDfXhS9TrnGWW0UTYg0AXP2e6cudX1VXluURTmS2UuGgliQ+tWyHR20qpTCeDAc/D2o/5j+C1BLAwQUAAAACABGqjJd4rv8TGIAAAB5AAAAEAAAAHdvcmQvaGVhZGVyMS54bWwdzUEOgCAMBMCvGB9g0YMHgpz9BlEUEwpNS4LPF7zMZrOHNVWHk4cXYxJdtzGUQhpAjuDRyZTJp7ZdmdGVVvmGmvkkzocXedKNERalVkD3pNGaqqnDnWL32UDPLv/Sb3u0H1BLAQIUAxQAAAAIAEaqMl0TPcbemwAAANAAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLAQIUAxQAAAAIAEaqMl3iu/xMYgAAAHkAAAAQAAAAAAAAAAAAAACAAcoAAAB3b3JkL2hlYWRlcjEueG1sUEsFBgAAAAAAAAAAfQAAAFoBAAAAAA==",
      { text: "\nvisible\n\nH1\n", members: 2, decl: 329 },
    ],
    [
      "z_count_more.docx",
      "UEsDBBQAAAAIAEaqMl0TPcbemwAAANAAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjk0OwiAQha9C2FuqC2Oa/uw8gR6AlrElgRnCYGtvL9SFm+/lZTJfXjt8vBMrRLaEnTxXtRSAExmLcyefj/vpJgUnjUY7QujkDiyHvt0aQ9PbAyaRBcjN1sklpdAoxdMCXnNFATDfXhS9TrnGWW0UTYg0AXP2e6cudX1VXluURTmS2UuGgliQ+tWyHR20qpTCeDAc/D2o/5j+C1BLAwQUAAAACABGqjJd4rv8TGIAAAB5AAAAEAAAAHdvcmQvaGVhZGVyMS54bWwdzUEOgCAMBMCvGB9g0YMHgpz9BlEUEwpNS4LPF7zMZrOHNVWHk4cXYxJdtzGUQhpAjuDRyZTJp7ZdmdGVVvmGmvkkzocXedKNERalVkD3pNGaqqnDnWL32UDPLv/Sb3u0H1BLAQIUAxQAAAAIAEaqMl0TPcbemwAAANAAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLAQIUAxQAAAAIAEaqMl3iu/xMYgAAAHkAAAAQAAAAAAAAAAAAAACAAcoAAAB3b3JkL2hlYWRlcjEueG1sUEsFBgAAAAAFAAUAfQAAAFoBAAAAAA==",
      { text: "\nvisible\n\nH1\n", members: 2, decl: 329 },
    ],
    [
      "z_trailing.docx",
      "UEsDBBQAAAAIAEaqMl17ZwcGmwAAANEAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjsEOgjAMhl9l6V2GHowhgDefQB9gbBVIWLusU+Tt3fDg5Wv+/OnXttePX9Qbo8xMHRyrGhSSZTfT2MHjfjtcQEky5MzChB1sKHDt27VxbF8eKaksIGnWDqaUQqO12Am9kYoDUu6eHL1JOcZRrxxdiGxRJPv9ok91fdbezARFObDbygwFsSD1gxFU+VarSyqMO8PO34b+f9N/AVBLAQIUAxQAAAAIAEaqMl17ZwcGmwAAANEAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAADKAAAAAAAAAAAAAAAAAAAA",
      { text: "\nbase doc\n", members: 1, decl: 209 },
    ],
    [
      "z_trailing_txt.docx",
      "UEsDBBQAAAAIAEaqMl17ZwcGmwAAANEAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjsEOgjAMhl9l6V2GHowhgDefQB9gbBVIWLusU+Tt3fDg5Wv+/OnXttePX9Qbo8xMHRyrGhSSZTfT2MHjfjtcQEky5MzChB1sKHDt27VxbF8eKaksIGnWDqaUQqO12Am9kYoDUu6eHL1JOcZRrxxdiGxRJPv9ok91fdbezARFObDbygwFsSD1gxFU+VarSyqMO8PO34b+f9N/AVBLAQIUAxQAAAAIAEaqMl17ZwcGmwAAANEAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAADKAAAAAABHQVJCQUdFLUFGVEVSLUVPQ0Q=",
      { text: "\nbase doc\n", members: 1, decl: 209 },
    ],
    [
      "z_comment.docx",
      "UEsDBBQAAAAIAEaqMl3efNrGnQAAANUAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjsEOwiAMhl+FcHdMD8YsY7v5BPoACHUjGS2h6NzbC/Pg5Wv6N/3afvyERbwhsSfU8ti0UgBach4nLe+36+EiBWeDziyEoOUGLMehXztH9hUAsygC5G7Vcs45dkqxnSEYbigCltmTUjC5tGlSKyUXE1lgLv6wqFPbnlUwHmVVPshttcaKVJGH1edZWAr1VK9qUpl2xp2/LfX/aPgCUEsBAhQDFAAAAAgARqoyXd582sadAAAA1QAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAAMwAAAANAGhlbGxvIGNvbW1lbnQ=",
      { text: "\nwith comment\n", members: 1, decl: 213 },
    ],
    [
      "z_comment_sig.docx",
      "UEsDBBQAAAAIAEaqMl1gt2g1mwAAANQAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjsEOwiAMhl+F9O6YHoxZxnbzCfQBEHAjGS2h6NzbC/Pg5Wv6N/3afvyERbxdYk+o4Ni0IBwash4nBffb9XABwVmj1QuhU7A5hnHo186SeQWHWRQBcrcqmHOOnZRsZhc0NxQdltmTUtC5tGmSKyUbExnHXPxhkae2PcugPUJVPshutcaKVJEHQ2G/wn7qZQ0q086487ck/w8NX1BLAQIUAxQAAAAIAEaqMl1gt2g1mwAAANQAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAADKAAAAIgBQSwUGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "REJECT:format_mismatch",
    ],
    [
      "z_prepended.docx",
      "IyEvYmluL3NoCmVjaG8gc2Z4ClBLAwQUAAAACABGqjJde2cHBpsAAADRAAAAEQAAAHdvcmQvZG9jdW1lbnQueG1sRY7BDoIwDIZfZeldhh6MIYA3n0AfYGwVSFi7rFPk7d3w4OVr/vzp17bXj1/UG6PMTB0cqxoUkmU309jB4347XEBJMuTMwoQdbChw7du1cWxfHimpLCBp1g6mlEKjtdgJvZGKA1Lunhy9STnGUa8cXYhsUST7/aJPdX3W3swERTmw28oMBbEg9YMRVPlWq0sqjDvDzt+G/n/TfwFQSwECFAMUAAAACABGqjJde2cHBpsAAADRAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAygAAAAAA",
      { text: "\nbase doc\n", members: 1, decl: 209 },
    ],
    [
      "z_size_lie.docx",
      "UEsDBBQAAAAIAEaqMl3+HPt1qAwAANAHAAARAAAAd29yZC9kb2N1bWVudC54bWztzE1Kw0AAhuGrhOxtqguR0qQg/uDGlR4gTUZbaGZCklp7e5veQniexTszDHzrzW93yH7CMO5TLPPbxTLPQmxSu4/fZf758XLzkGfjVMe2PqQYyvwcxnxTrU+rNjXHLsQpuwzEcXUq89009auiGJtd6OpxkfoQL39faejq6fIcvotTGtp+SE0Yx8t+dyjulsv7oqv3MZ8nt6k9z2c/Z5gzVY9vrxkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMA/9/z+tC5Oq6maO1zbX7tN7fl6aVNz7EKcqj9QSwECFAMUAAAACABGqjJd/hz7dagMAADQBwAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAA1wwAAAAA",
      "REJECT:invalid_archive",
    ],
    [
      "z_trunc_deflate.docx",
      "UEsDBBQAAAAIAEaqMl2W64wIogAAACEDAAARAAAAd29yZC9kb2N1bWVudC54bWztkjsOwjAQRK9iuScOFAhF+XScAA5g7CWJFO9a9oaQ22OHggtQpnk7o5WmenX3dpN4QYgjYSOPRSkFoCE7Yt/I++16uEgRWaPVEyE0coUou7ZeKktmdoAs0gDGamnkwOwrpaIZwOlYkAdMvycFpznV0KuFgvWBDMSY9t2kTmV5Vk6PKPPkg+yar88IGdxymNFoBuFA7HnP/8q1ynZlho1+49dA9bO7/QBQSwECFAMUAAAACABGqjJdluuMCKIAAAAhAwAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAA1wAAAAAA",
      "REJECT:invalid_archive",
    ],
    [
      "z_localname.docx",
      "UEsDBBQAAAAIAEaqMl1E/9uyoQAAANwAAAARAAAAV09SRC9kb2N1bWVudC54bWxFjkEOwiAQRa9C2FuqC2Oa0u48gR4AYWybwAxh0NrbC3Xh5v1Mfv7L9OMnePGGxAuhlsemlQLQkltw0vJ+ux4uUnA26IwnBC03YDkO/do5sq8AmEURIHerlnPOsVOK7QzBcEMRsHRPSsHkcqZJrZRcTGSBufiDV6e2PatgFpRV+SC31YwVqSIPnqzxAk0AERYuJjv3qhaVaWfc+Rur/2PDF1BLAQIUAxQAAAAIAEaqMl1E/9uyoQAAANwAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAADQAAAAAAA=",
      "REJECT:invalid_archive",
    ],
    [
      "d_space.docx",
      "UEsDBBQAAAAIAEaqMl0O43IHzgAAADYBAAARAAAAd29yZC9kb2N1bWVudC54bWyFj01OAzEMha8SZT91pkCpRjPprieAA4TEtCNNfmSHTnsIxLo36ZlA3IGkEkJISGyeZfn583O/OfpJHJB4jGGQ7UJJgcFGN4bdIB8fts1aCs4mODPFgIM8IcuN7ufORfviMWRRAIG7eZD7nFMHwHaP3vAiJgxl9hzJm1xa2sEcySWKFpkL30+wVGoF3oxBVuRTdKdaUxWqcqV3nIwtpxMhIx1Q6s/z6/vl8vF27qF4dFX6b0f86dWqVU27vLlt7lb3618WuAaB71jw87L+AlBLAQIUAxQAAAAIAEaqMl0O43IHzgAAADYBAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAAD9AAAAAAA=",
      { text: "\n홍길동 010-1234-5678\n", members: 1, decl: 310 },
    ],
    [
      "e_zip64.docx",
      "UEsDBC0AAAAIAAAAIQAcPVTy//////////8RABQAd29yZC9kb2N1bWVudC54bWwBABAAswAAAAAAAACFAAAAAAAAAEXOXQ7CIAwH8KssHGBFY/ZAGDvLPupGslJSUNTTO+aDL7+m/adN7fCivXmiJM+hV5dWq8HZYhaeH4QhN0cckim92nKOBiDNG9KYWo4YjuzOQmM+WlmhsCxReMaUfFhph6vWHdDog6onJ17etcaKVLL7+NjdGkKaUCzUSVVO4+lvC/4fuS9QSwECLQMtAAAACAAAACEAHD1U8oUAAACzAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAyAAAAAAA",
      { text: "\nzip64 member\n", members: 1, decl: 179 },
    ],
    [
      "e_ver64.docx",
      "UEsDBBQAAAAIACCsMl0LcxFzfgAAAKoAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjkEOwyAMBL8S8YCY9tADIuQtFGiCFGNkaGl/X0gPvYx3tZa9en3jMb0Cl0hpEZdZitXopjy5J4ZUpx6notoi9lqzAihuD2jLTDmknj2I0dZueYNG7DOTC6XEtOEBVylvgDYmMU7eyX/GzAM8UE1/rGGIQT6ZT/6W4V/EfAFQSwECFANAAAAACAAgrDJdC3MRc34AAACqAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAArQAAAAAA",
      "REJECT:invalid_archive",
    ],
    [
      "e_stored_small.docx",
      "UEsDBBQAAAAAACCsMl1hSAd3sQAAALEAAAARAAAAd29yZC9kb2N1bWVudC54bWw8P3htbCB2ZXJzaW9uPSIxLjAiPz48dzpkb2N1bWVudCB4bWxuczp3PSJodHRwOi8vc2NoZW1hcy5vcGVueG1sZm9ybWF0cy5vcmcvd29yZHByb2Nlc3NpbmdtbC8yMDA2L21haW4iPjx3OmJvZHk+PHc6cD48dzpyPjx3OnQ+c3RvcmVkIGxpZTwvdzp0PjwvdzpyPjwvdzpwPjwvdzpib2R5Pjwvdzpkb2N1bWVudD5QSwECFAMUAAAAAAAgrDJdYUgHd7EAAACsAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAA4AAAAAAA",
      "REJECT:invalid_archive",
    ],
    [
      "e_nulname.docx",
      "UEsDBBQAAAAIACCsMl3GbuXagQAAAK8AAAARAAAAd29yZC9kb2N1bWVudC54bWxFzsEOgyAMBuBXMTyAdTvsYBCfhSFTEtqSgrK9/cQddvmaP3/aVM9vjN3hJQemSd36Qc1G13Fht6On0p015bFOaisljQDZbR5t7jl5OrsXC9pyRlmhsixJ2PmcA60Y4T4MD0AbSLWTT14+baaGNIqhPXZk0WtoqSmX6fK3Af9vzBdQSwMEFAAAAAgAIKwyXdQc0QEGAAAABAAAAAwAAAB3b3JkL2EAYi54bWyzSdS3AwBQSwECFAMUAAAACAAgrDJdxm7l2oEAAACvAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwECFAMUAAAACAAgrDJd1BzRAQYAAAAEAAAADAAAAAAAAAAAAAAAgAGwAAAAd29yZC9hAGIueG1sUEsFBgAAAAACAAIAeQAAAOAAAAAAAA==",
      { text: "\nnul name\n", members: 2, decl: 179 },
    ],
    [
      "e_flag5.docx",
      "UEsDBBQAAAAIACCsMl1MVSF3fgAAAKsAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzjEOwyAMBdCrRBwgph06oISchQIhSICRoaG9fSEdujzb+pblZXvHMJ2Wise0stvM2SaXJgzqV7SpTj1ORbSVHbVmAVD0YaMqM2aberYjRVX7SA4aksmE2pbik4sB7pw/ICqf2Dj5RPMZNQ9oUOUelFtgdEO6zJe/bfh/Ir9QSwECFAMUACAACAAgrDJdTFUhd34AAACrAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAArQAAAAAA",
      "REJECT:invalid_archive",
    ],
    [
      "e_flag6.docx",
      "UEsDBBQAAAAIACCsMl1MVSF3fgAAAKsAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzjEOwyAMBdCrRBwgph06oISchQIhSICRoaG9fSEdujzb+pblZXvHMJ2Wise0stvM2SaXJgzqV7SpTj1ORbSVHbVmAVD0YaMqM2aberYjRVX7SA4aksmE2pbik4sB7pw/ICqf2Dj5RPMZNQ9oUOUelFtgdEO6zJe/bfh/Ir9QSwECFAMUAEAACAAgrDJdTFUhd34AAACrAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAArQAAAAAA",
      "REJECT:invalid_archive",
    ],
    [
      "e_overlap.docx",
      "UEsDBBQAAAAIACCsMl2+QBmeiAAAAOcBAAARAAAAd29yZC9kb2N1bWVudC54bWztkUEOAiEMRa9COMAUXbggDHMWBJwhAUoKOnp7YVy4d+3mvTQ/aZNftTxTZA9PNWCe+WkSfNFqlw7tPfncWI9zlfvMt9aKBKh288nUCYvPPbshJdP6SCvsSK4QWl9ryGuKcBbiAsmEzMfKK7rXcBmggaaxX46msL9/s4LR4iAdLAc/TcP3i/oNUEsDBBQAAAAIACCsMl2cGG/jfgAAAKgAAAAQAAAAd29yZC9oZWFkZXIxLnhtbEXOMQ7DIAwF0KtEHCCmHTogQtZeIwWaIAWMbFLa2xfSocv7sr5lWc/vuA8vTxwwTeIySjEbXZVDe0SfytDqxKpOYislKwC2m48Lj5h9at0TKS6ljbRCRXKZ0HrmkNa4w1XKG8QlJNFPPtB9euYOdYq5a+jRpdN8+luF/xvmC1BLAQIUAxQAAAAIACCsMl2+QBmesAAAAOcBAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLAQIUAxQAAAAIACCsMl2cGG/jfgAAAKgAAAAQAAAAAAAAAAAAAACAAbcAAAB3b3JkL2hlYWRlcjEueG1sUEsFBgAAAAACAAIAfQAAAGMBAAAAAA==",
      "REJECT:invalid_archive",
    ],
    [
      "e_cdsize_small.docx",
      "UEsDBBQAAAAIACCsMl0fx8FngAAAAK0AAAARAAAAd29yZC9kb2N1bWVudC54bWxFzsEOwiAMBuBXWXiAdXrwQBh7FgTcSAYlLQ716YV58PK1zd80Vcsr7sPhiQOmWVzGSSxaVenQPqNPZWhxYllnsZWSJQDbzUfDI2afWvZAiqa0kVaoSC4TWs8c0hp3uE7TDaIJSfSTd3TvXnOHOkVbx+HjFfS+S6f59LcP/1/0F1BLAwQUAAAACAAgrDJduJyrhhIAAAAQAAAAEAAAAHdvcmQvaGVhZGVyMS54bWyzUXTxdw6JDHBVqLCzSdS3AwBQSwECFAMUAAAACAAgrDJdH8fBZ4AAAACtAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwECFAMUAAAACAAgrDJduJyrhhIAAAAQAAAAEAAAAAAAAAAAAAAAgAGvAAAAd29yZC9oZWFkZXIxLnhtbFBLBQYAAAAAAgACAHMAAADvAAAAAAA=",
      "REJECT:invalid_archive",
    ],
    [
      "e_cdsize_big.docx",
      "UEsDBBQAAAAIACCsMl0fx8FngAAAAK0AAAARAAAAd29yZC9kb2N1bWVudC54bWxFzsEOwiAMBuBXWXiAdXrwQBh7FgTcSAYlLQ716YV58PK1zd80Vcsr7sPhiQOmWVzGSSxaVenQPqNPZWhxYllnsZWSJQDbzUfDI2afWvZAiqa0kVaoSC4TWs8c0hp3uE7TDaIJSfSTd3TvXnOHOkVbx+HjFfS+S6f59LcP/1/0F1BLAwQUAAAACAAgrDJduJyrhhIAAAAQAAAAEAAAAHdvcmQvaGVhZGVyMS54bWyzUXTxdw6JDHBVqLCzSdS3AwBQSwECFAMUAAAACAAgrDJdH8fBZ4AAAACtAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwECFAMUAAAACAAgrDJduJyrhhIAAAAQAAAAEAAAAAAAAAAAAAAAgAGvAAAAd29yZC9oZWFkZXIxLnhtbFBLBQYAAAAAAgACAIcAAADvAAAAAAA=",
      "REJECT:invalid_archive",
    ],
    [
      "e_badextra.docx",
      "UEsDBBQAAAAIAAAAIQAcOePYgQAAALAAAAARAAYAd29yZC9kb2N1bWVudC54bWyZmTIAYWJFzjEOwyAMBdCrIA4Q0w4dECFnIUATpICRoSW9fSEdujzr68uW1XLGg709lYBp5rdJ8EWrJh3aV/Spsl6nItvM91qzBCh299GUCbNPvXsiRVN7pA0aksuE1pcS0hYPuAvxgGhC4uPkiu4zZh7QoOrVOObPSkbBiEO6zJe/Ffi/o79QSwECFAMUAAAACAAAACEAHDnj2IEAAACwAAAAEQAGAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWyZmTIAYWJQSwUGAAAAAAEAAQBFAAAAtgAAAAAA",
      "REJECT:invalid_archive",
    ],
    [
      "e_upath.docx",
      "UEsDBBQAAAAIACCsMl0TZphxfwAAAKwAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzjEOwyAMBdCrRBwgph06IELOQoEGpICRIaG9fSEdujzb+pZlub7jPp2OSsC0sNvM2apkExbNEV2qU49TEW1hvtYsAIrxLuoyY3apZy+kqGsfaYOGZDOhcaWEtMUd7pw/IOqQ2Dj5RPsZNQ9oUNWRdfUSRjuky3z5W4f/K+oLUEsDBBQAAAAIAAAAIQDUHNEBBgAAAAQAAAAKABQAd29yZC94LnhtbHVwEAABaINJVC4uL2V2aWwueG1ss0nUtwMAUEsBAhQDFAAAAAgAIKwyXRNmmHF/AAAArAAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsBAhQDFAAAAAgAAAAhANQc0QEGAAAABAAAAAoAFAAAAAAAAAAAAIABrgAAAHdvcmQveC54bWx1cBAAAWiDSVQuLi9ldmlsLnhtbFBLBQYAAAAAAgACAIsAAADwAAAAAAA=",
      "REJECT:unsafe_archive_path",
    ],
    [
      "dup_cdsize_fixed.hwpx",
      "UEsDBBQAAAAIAGesMl1+QAwpEQAAAA8AAAAVAAAAQ29udGVudHMvc2VjdGlvbjAueG1ssymwsymxS7TRL7Gz0S+wAwBQSwECFAMUAAAACABnrDJdfkAMKREAAAAPAAAAFQAAAAAAAAAAAAAAgAEAAAAAQ29udGVudHMvc2VjdGlvbjAueG1sUEsBAhQDFAAAAAgAZ6wyXX5ADCkRAAAADwAAABUAAAAAAAAAAAAAAIABAAAAAENvbnRlbnRzL3NlY3Rpb24wLnhtbFBLBQYAAAAAAgACAIYAAABEAAAAAAA=",
      "REJECT:duplicate_archive_member",
    ],
    [
      "dup_cdsize_stale.hwpx",
      "UEsDBBQAAAAIAGesMl1+QAwpEQAAAA8AAAAVAAAAQ29udGVudHMvc2VjdGlvbjAueG1ssymwsymxS7TRL7Gz0S+wAwBQSwECFAMUAAAACABnrDJdfkAMKREAAAAPAAAAFQAAAAAAAAAAAAAAgAEAAAAAQ29udGVudHMvc2VjdGlvbjAueG1sUEsBAhQDFAAAAAgAZ6wyXX5ADCkRAAAADwAAABUAAAAAAAAAAAAAAIABAAAAAENvbnRlbnRzL3NlY3Rpb24wLnhtbFBLBQYAAAAAAgACAEMAAABEAAAAAAA=",
      "REJECT:invalid_archive",
    ],
  ];
  for (const [file, base64, python] of cases) {
    it(`readTextBounded === Python: ${file}`, async () => {
      expect(await boundedOutcome(fixture(file, base64))).toEqual(python);
    });
  }

  it("선언 크기를 속인 멤버는 정책 한도와 무관하게 invalid_archive (Python 실측)", async () => {
    const sizeLie = cases.find((c) => c[0] === "z_size_lie.docx");
    expect(sizeLie).toBeDefined();
    const path = fixture("z_size_lie_tight.docx", sizeLie ? sizeLie[1] : "");
    const policy = new FileReadPolicy({ maxArchiveMemberBytes: 1024 * 1024 });
    expect(await boundedOutcome(path, policy)).toBe("REJECT:invalid_archive");
  });

  it("ENOTDIR 경로는 file_unavailable (Python: is_symlink/stat 의 OSError 흡수)", async () => {
    const file = fixture("plain.md", Buffer.from("# md\n").toString("base64"));
    expect(await boundedOutcome(join(file, "child.txt"))).toBe("REJECT:file_unavailable");
  });

  it("max_text_chars 는 코드 포인트 단위 (Python len)", async () => {
    const path = fixture("astral.txt", Buffer.from("😀".repeat(10)).toString("base64"));
    const policy = new FileReadPolicy({ maxTextChars: 15 });
    expect(await boundedOutcome(path, policy)).toEqual({
      text: "😀".repeat(10),
      members: 0,
      decl: 0,
    });
    expect(await boundedOutcome(path, new FileReadPolicy({ maxTextChars: 9 }))).toBe(
      "REJECT:extracted_text_too_large",
    );
  });
});

describe("추출 결과·예외 — Python 과 같은 텍스트, 같은 예외 클래스명·메시지", () => {
  type Outcome = string | { err: string; msg: string };
  const cases: Array<[file: string, base64: string, raw: Outcome, bounded: string | null]> = [
    [
      "enc_latin1.docx",
      "UEsDBBQAAAAIAJqtMl0iZLjZmQAAAMMAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjksOwjAMRK8SZd+6rQQqVT9rViw4QUjSj9TEkRMoHJklNyApCzZvPBp75HZ4mpU9NPkFbcfLvOBMW4lqsVPHz9dLVteHU1byoW+3RqG8G20Di0fWN1vH5xBcA+DlrI3wOTptYzYiGRGipQk2JOUIpfY+dpoVqqI4ghGL5anyhuqV1CVQQuilGN/s00KaE2mn2/nbh/8v/RdQSwECFAMUAAAACACarTJdImS42ZkAAADDAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAyAAAAAAA",
      "\ncafé ñ\n",
      "\ncafé ñ\n",
    ],
    [
      "enc_latin1_lower.docx",
      "UEsDBBQAAAAIAJqtMl3I4+fhkQAAAMEAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjksOgzAMRK+CsgdDpVYU8TlLmgSIROLIDqU9cm/RhC66eePR2CP308ttxdMQW/SDaKpaFMYr1NYvg7CMZdte72UjprE/Oo1qd8bHIh157o5BrDGGDoDVapzkCoPxKZuRnIzJ0gIHkg6EyjCnTrfBpa5v4KT1Ilc+UL+zhgzKiKOS86eHPGXSyXDytw3/T8YvUEsBAhQDFAAAAAgAmq0yXcjj5+GRAAAAwQAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAAMAAAAAAAA==",
      "\ncafé\n",
      "\ncafé\n",
    ],
    [
      "enc_latin1_alias.docx",
      "UEsDBBQAAAAIAJqtMl0m5rbBjAAAAL0AAAARAAAAd29yZC9kb2N1bWVudC54bWxFjkESgyAMRa/icACjXXThiJ6FAiozkDCBSnvk3qJgF928nz8/+ZN5fQXfnZaTI5Ri7AfRWdRkHO5SeJUdjmJd5jIZ0s9gMXf1ANNUpDhyjhNA0ocNKvUULdZsIw4qV8s7FGITmbRNqfYFD7dhuENQDkWrfJB5N40N3JAXrbbPDG1q5Ivx4m8b/p8sX1BLAQIUAxQAAAAIAJqtMl0m5rbBjAAAAL0AAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAAC7AAAAAAA=",
      "\ncafé\n",
      "\ncafé\n",
    ],
    [
      "enc_ascii.docx",
      "UEsDBBQAAAAIAJqtMl0BnU4YlgAAAMYAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjr0OwjAMhF8lyk5dGBiq/ggxda54gJCENlJjR06g8PYkZWD5rPPpTtcOb7+Kl+XoCDt5rGopLGoyDudO3qbDZbqOoxz6dmsM6ae3mESOYGy2Ti4phQYg6sV6FSsKFrP3IPYqZckzbMQmMGkbY270K5zq+gxeOZSl8k7mU24o4ILUhzW7QkXtXAvlUcg7w85fCP6D+i9QSwECFAMUAAAACACarTJdAZ1OGJYAAADGAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAxQAAAAAA",
      "\nplain ascii\n",
      "\nplain ascii\n",
    ],
    [
      "enc_ascii_hi.docx",
      "UEsDBBQAAAAIAJqtMl1nnmajlQAAAL8AAAARAAAAd29yZC9kb2N1bWVudC54bWxFjksOwjAMRK9SZU9dWLCo+hFi1XXFAUKSfqTGjpxA4MjcgqQs2LzxaOyRm/5lt+Jp2K+ErTiWlSgMKtIrzq24jYfLeB0G0XdNrDWphzUYinSCvo6tWEJwNYBXi7HSl+QMpmwitjIkyzNEYu2YlPE+NdoNTlV1BitXFLnyTvqd1WVwRuiUnD4N5CmTd7qdv234f9J9AVBLAQIUAxQAAAAIAJqtMl1nnmajlQAAAL8AAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAADEAAAAAAA=",
      "\n",
      "\n",
    ],
    [
      "enc_utf8_decl.docx",
      "UEsDBBQAAAAIAJqtMl3qSsD8nQAAAMEAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjssNwjAQRFuJfCcbOCAU5XOjAigg2CaJFO9aa0OgCMQ5naQmED1ghwOXNxrN7GiL+maG5KrZ9YSlWKeZSDRKUj22pTge9qudqKtizBXJi9Hok9BHl4+l6Ly3OYCTnTaNS8lqDNmZ2DQ+WG5hJFaWSWrnwpwZYJNlWzBNjyJOnkjdo9oIjvDVZ3q85vn9nAqINpIX2oW/E/i/U30BUEsBAhQDFAAAAAgAmq0yXepKwPydAAAAwQAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAAMwAAAAAAA==",
      "\n홍길동\n",
      "\n홍길동\n",
    ],
    [
      "enc_utf8_lower.docx",
      "UEsDBBQAAAAIAJqtMl0VplNJmQAAAMEAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjksOwjAMRK9SZU9dWCBU9XOWkqQfqbEjJ23hEIh1b9IzgbgDSVmweaPRjEcu6psZk1mzGwhLcUwzkWiUpAbsSjH59nARdVUsuSI5GY0+CX10+VKK3nubAzjZa9O4lKzGkLXEpvHBcgcLsbJMUjsX5swIpyw7g2kGFHHySuoe1UZwhK8+6+O1be/nWkC0kbzT7vydwP+d6gtQSwECFAMUAAAACACarTJdFaZTSZkAAADBAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAyAAAAAAA",
      "\n홍길동\n",
      "\n홍길동\n",
    ],
    [
      "enc_utf8_bad.docx",
      "UEsDBBQAAAAIAJqtMl1tV1OijAAAALkAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjkEOwiAURK/SsLe/ujCmKXTnCfQAFbAlKf+TD4qeXqEu3LzJZCaTGcaXX5un5egIpdi3nWgsajIOZymul/PuJEY15N6QfniLqSl9jH2WYkkp9ABRL9ZPsaVgsWR3Yj+lYnmGTGwCk7Yxljm/wqHrjuAnh6JO3si8q4YKrkjqM0CVSt4YNv6q8L+hvlBLAQIUAxQAAAAIAJqtMl1tV1OijAAAALkAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAAC7AAAAAAA=",
      "\n",
      "\n",
    ],
    [
      "enc_utf16_decl_utf8bytes.docx",
      "UEsDBBQAAAAIAJqtMl34m8EAnQAAAMIAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjk0OgjAUhK9CupeHLlgQfnaeQA+AbQUS+l7zWkUPYVxzE86k8Q62uHDzTSaTmUzZ3MyYXDW7gbAS2zQTiUZJasCuEsfDfrPNRVOXU6FIXoxGn4QCumKqRO+9LQCc7LVpXUpWY8jOxKb1wXIHE7GyTFI7F/bMCLssy8G0A4o4eSJ1j2ojOMLXn/nxWpb3cy4h2kheaVf+KvC/U38BUEsBAhQDFAAAAAgAmq0yXfibwQCdAAAAwgAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAAMwAAAAAAA==",
      "\n",
      "\n",
    ],
    [
      "enc_utf16_nobom_le.docx",
      "UEsDBBQAAAAIAJqtMl1P4Mw8wwAAAHgBAAARAAAAd29yZC9kb2N1bWVudC54bWxtUEsOgjAUnKMQ9lJ0YQxB2LFzpwdQQTGR0pT6u5Qb72LibZwWbFiYLjrvzcx706bIcUeDMwJcUUGjwwktJJYIMUWEmHdARmLPfklW4ujYDdYoMKFqzipHhhQ3JNS01F441boM3f0GydkJFdZbs2+gWAuejvqa6gZb4oh+5by978BaO84MrGYCwUkWldRqt7Ei2w35rE9gxvQx0wnntkzoU+7cax6+Vh5pjwzR6r14fl6p29d3fliPsBrh8WTx90cyfAFQSwECFAMUAAAACACarTJdT+DMPMMAAAB4AQAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAA8gAAAAAA",
      "\n홍길동\n",
      "\n홍길동\n",
    ],
    [
      "enc_utf16_nobom_be.docx",
      "UEsDBBQAAAAIAJqtMl2DyUb+wQAAAHgBAAARAAAAd29yZC9kb2N1bWVudC54bWxtUEsOgjAUnKMQ9lJ0YQxB2LFzpwdQQTGR0pT6u5Qb72LibZwWbFgYFp15M/M6BSly3NHgjABXVNDocEILiSVCTBEh5hlQkdhzXlKVODp1gzUKTOiak+XIkOKGhJ6W3gu32pRhur9BcndCh83WnBsocsGvo7+mu8GWOGJeuWyfO5Brp5lB1WwguMmikl7tbqyodkM/mxOYsX3MdsKlrRL6ljv3mofnyiPtkUH2Xj0Xrw+5+E081iOsRni8Wfz9I9kXUEsBAhQDFAAAAAgAmq0yXYPJRv7BAAAAeAEAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAAPAAAAAAAA==",
      "\n홍길동\n",
      "\n홍길동\n",
    ],
    [
      "enc_utf16_bom.docx",
      "UEsDBBQAAAAIAJqtMl1nHjHOxQAAAHoBAAARAAAAd29yZC9kb2N1bWVudC54bWxtUEsOgjAUnKMQ9lJ1YQxB2LlzpwdQQTGR0pT6u5Qb72LiZdRpwYaF6aLz3sy8N+3nnSDDFRWOCHBGAY0GB9SQmCHECBGGvAMyElv2c7ISe8eusMQcA6omrDKkSHBBTE1N7YlTrcvQ3W6QnB1TYb0l+waKteBpqC+prrAmjuhXztv6dqy140zHaiYQnGRRTq12GwuyTZfP+gTGTD9kOuHclgl9yo17zc3XyiPtkSFaPKf31yNx+9rOD+seVj3cnyz+/kiKL1BLAQIUAxQAAAAIAJqtMl1nHjHOxQAAAHoBAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAAD0AAAAAAA=",
      "\n홍길동\n",
      "\n홍길동\n",
    ],
    [
      "enc_utf16_bom_nodecl.docx",
      "UEsDBBQAAAAIAJqtMl1ccnElmwAAACwBAAARAAAAd29yZC9kb2N1bWVudC54bWxtkEEKwjAQRd9RpAew4kJEam/gIdTWVrAa0kj1Um68i+Bl1N9EQxeSzZv58zIh71dGx4KCE1vONJQccYy4iA/iVmnHkoRafYdRneq0mq813bAWj+Ub7wZvp9r6zH1TSyWr81Ro1vqNpdKWvbzKeylTJjozUW/3SUJOeOVGTsE11iaSjeREq8f89rxnfl/o/NgO2Ax4eHP690dyPlBLAQIUAxQAAAAIAJqtMl1ccnElmwAAACwBAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAADKAAAAAAA=",
      "\n홍길동\n",
      "\n홍길동\n",
    ],
    [
      "enc_utf16le_name.docx",
      "UEsDBBQAAAAIAJqtMl3BzoZXxgAAAHwBAAARAAAAd29yZC9kb2N1bWVudC54bWxtUEsOgjAUnKMQ9lJ1YQxBWOlKd3oAFRQTKU2pv0u58S4m3sZpwYaF6aLz3nzeaxNkuKPCGQGuKKDR4IQaEjOEGCHCkHdARmLPfk5W4ujYDdZYYEDVBEvM2cmQIsENMXU19RcmW6dhQjtFMj+mwvpL9g0Ua8HTUF9SXWFLHNGvnLf1HVhrx5mO1dxCMMminFrtJhZkm25H6xMY8wVDbiic2zKh33LnXvTwtfJIe2SIVu/p8/NK3Ly288O6h1UP95PF3x9J8QVQSwECFAMUAAAACACarTJdwc6GV8YAAAB8AQAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAA9QAAAAAA",
      "\n홍길동\n",
      "\n홍길동\n",
    ],
    [
      "enc_utf8_decl_utf16bytes.docx",
      "UEsDBBQAAAAIAJqtMl3kGNJ9xAAAAHgBAAARAAAAd29yZC9kb2N1bWVudC54bWxtkD0OgkAQhd9RCL0sWhhCEDo7Oz2ACoqJLGRZ/y5l411MvIz6dsENhaHgm3nvzQx83gkyXFHhCA9nFFBocUANiRl8jBEg5NujIrFlP6cqsbfqCkvMMUJEzpAiwQUxHTWdJ840Gc1sN19yckyHSZbsazSsBZ+W/pLuCmtywHxjs11ux1pZTfeq4n7BSYZyepXdWFBt++tMTmDC20NMSSZtFN9dubHfcnN140g50qTFM7q/Hond13V+rAbcDHg4Wfz9Iym+UEsBAhQDFAAAAAgAmq0yXeQY0n3EAAAAeAEAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAAPMAAAAAAA==",
      "\n",
      "\n",
    ],
    [
      "enc_euckr.docx",
      "UEsDBBQAAAAIAJqtMl0MemTUlgAAAL8AAAARAAAAd29yZC9kb2N1bWVudC54bWxFjjsSwjAMRK+ScU8UKCgy+ZwlsUWSIZY8skPgTFQU1LSchHNgh4LmrXZW2lHVXu2cXVD8xFSrfV6oDEmzmWioFS56dxbVNtVaGtaLRQpZPCBfrrUaQ3AlgNcj2s7n7JBidmKxXYhWBlhZjBPW6H3sszMciuIItptIpcqezS2pS5CE0Lzvj8/zVUGaE2Wj2/jbh/8vzRdQSwECFAMUAAAACACarTJdDHpk1JYAAAC/AAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAxQAAAAAA",
      { err: "ValueError", msg: "multi-byte encodings are not supported" },
      "REJECT:extract_failed",
    ],
    [
      "enc_cp949.docx",
      "UEsDBBQAAAAIAJqtMl3OvhZ6lwAAAL4AAAARAAAAd29yZC9kb2N1bWVudC54bWxFjksOwjAMRK8S5QB1QQipVT9nKUloKzV25KQEzsSKBWu2nIRzkJQFmzcezWjkpr/aRVwM+5mwlbuilMKgIj3j2ErlqkMl+66JtSa1WoNBpD76OrZyCsHVAF5Nxg6+IGcwZWdiO4RkeYRIrB2TMt6nObvAviyPYIcZZZ48kb5ldRmcEbr3/fF5vhrIdyZvdBt/ffj/0n0BUEsBAhQDFAAAAAgAmq0yXc6+FnqXAAAAvgAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAAMYAAAAAAA==",
      { err: "ValueError", msg: "multi-byte encodings are not supported" },
      "REJECT:extract_failed",
    ],
    [
      "enc_cp1252.docx",
      "UEsDBBQAAAAIAJqtMl3xkQ+alAAAAMUAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjksOwjAMRK8SZU9dKsGi6ucsIUnbSI0dOYHAjutyC5KyYPPGo7FHHuan38XDcnSEozw3rRQWNRmH6yizQ0M5ns7dpZPzNOTekL57i0mUM4x9HuWWUugBot6sV7GhYLFkC7FXqVheIRObwKRtjKXV79C17RW8cihr5Y3Mq2qo4Io0abV8xHuAOlfywXDwtw//X6YvUEsBAhQDFAAAAAgAmq0yXfGRD5qUAAAAxQAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAAMMAAAAAAA==",
      "\ncafé €\n",
      "\ncafé €\n",
    ],
    [
      "enc_cp1252_ok.docx",
      "UEsDBBQAAAAIAJqtMl0Y/AWmjwAAAMMAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjksOwjAMRK9SZU9dKsGi6ucsIXHbSI0dxYHA7UnKgs0bj8YeeVze/mheGMUxTeradqpBMmwdbZPKjixnuVz7W6+WecyDZfP0SKkpZyRDntSeUhgAxOzotbQckEq2cvQ6FRs3yBxtiGxQpLT6A/quu4PXjlStfLD9VA0VsSLNRq84Qp0q48lw8rcN/0/mL1BLAQIUAxQAAAAIAJqtMl0Y/AWmjwAAAMMAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAAC+AAAAAAA=",
      "\ncafe\n",
      "\ncafe\n",
    ],
    [
      "enc_koi8.docx",
      "UEsDBBQAAAAIAJqtMl1M9XRRigAAALwAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjsESwiAMRH+F4W5TPThOp6XfQgFbxpIwAUX/XqgHL2+zs8lOxvkddvFynDzhJM9dL4VDQ9bjOskH+duJ5azGMlgyz+Awi3qAaSiT3HKOA0Aymws6dRQd1uxOHHSullcoxDYyGZdS7Qs7XPr+CkF7lK1yIftpGhu4ISu9mBHa0MgH48HfMvwfUV9QSwECFAMUAAAACACarTJdTPV0UYoAAAC8AAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAuQAAAAAA",
      "\nabc\n",
      "\nabc\n",
    ],
    [
      "enc_sjis.docx",
      "UEsDBBQAAAAIAJqtMl3un9xgjQAAAL8AAAARAAAAd29yZC9kb2N1bWVudC54bWxFjksOwjAMRK9S5QB1YcGi6ucoKE3SNqixIzsQuD1JWbB549HYIw/zOxzNy7F4wlFd2k41Dg1Zj9uoZPdruj+8qHkacm/JPIPD1JQblD6Pak8p9gBidhe0tBQdlmwlDjoVyxtkYhuZjBMpleGAa9fdIGiPqlYuZD9VYwVXpEkvZoA6VPLJePK3DP9Hpi9QSwECFAMUAAAACACarTJd7p/cYI0AAAC/AAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAvAAAAAAA",
      { err: "ValueError", msg: "multi-byte encodings are not supported" },
      "REJECT:extract_failed",
    ],
    [
      "enc_bogus.docx",
      "UEsDBBQAAAAIAJqtMl0qylLLjAAAAMEAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjksOgzAMRK+CsgfTLrpAfM4SkpREInZkh9LevglddPPGvxl5XN5xb16OJRBO6tb1qnFoyAbcJoXUymF8WyZqmcdzsGSO6DA3xYUynJPyOacBQIx3UUtHyWHZPYmjzqXlDU5im5iMEymhcYd73z8g6oCqRq5kP1VTBVfkWa9mhFpU8sV08XcM/0fmL1BLAQIUAxQAAAAIAJqtMl0qylLLjAAAAMEAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAAC7AAAAAAA=",
      { err: "LookupError", msg: "unknown encoding: no-such-enc" },
      "REJECT:extract_failed",
    ],
    [
      "enc_utf7.docx",
      "UEsDBBQAAAAIAJqtMl2LZP9cigAAALsAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjs0OgyAQhF/FcK9re2gT4s+zIKCSyC5ZUNq3L9hDL9/sZCaT7ae335vTcnSEg7i3nWgsajIO10Ecabm9xDT2WRrSh7eYmtLHKPMgtpSCBIh6s17FloLFki3EXqVieYVMbAKTtjGWOb/Do+ue4JVDUSdnMp+qoYIr0qhm3UM9KvliuPgrw/+R8QtQSwECFAMUAAAACACarTJdi2T/XIoAAAC7AAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAuQAAAAAA",
      { err: "ValueError", msg: "multi-byte encodings are not supported" },
      "REJECT:extract_failed",
    ],
    [
      "enc_squote.docx",
      "UEsDBBQAAAAIAJqtMl3vOA5PmAAAAMEAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjk0OgjAQha9C2HQFAyYaJBTWrlx4gtqWn4TONG0VPbK3sMWFm+/Ny5t5mW54mTV7aucXQs7qsmKZRklqwYmzy+1aNM3xXNRs6LutVSQfRmPI4hH6duP5HIJtAbyctRG+JKsxZiM5I0K0boKNnLKOpPY+dpoVDlV1AiMWzFPlndQ7qU1wCaGXYvx0kKZEt9Pu/G3D/5P+C1BLAQIUAxQAAAAIAJqtMl3vOA5PmAAAAMEAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAADHAAAAAAA=",
      "\ncafé\n",
      "\ncafé\n",
    ],
    [
      "ent_internal.docx",
      "UEsDBBQAAAAIAJqtMl0sF5psmQAAALwAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzj0PgjAQBuC/Ujo4esTBAWsTIx1ckKGDxDggLR8J/UhbA/x7KQ4uz92bu1yOJPn9yquSIYGeJGEFv/EKSYTZo7wUOcsxfVEyZcI0HyV1QLMatc+mM+5DsBmAb3qpar83Vup11hqn6rBG18FknLDONNL7QXdqhEOaHkHVg8bx5NuIJVYbcZFA5508LQRiG3WbdvO3Dv9X6BdQSwECFAMUAAAACACarTJdLBeabJkAAAC8AAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAyAAAAAAA",
      "\nxEXPANDEDy\n",
      "REJECT:xml_dtd_rejected",
    ],
    [
      "ent_nested.docx",
      "UEsDBBQAAAAIAJqtMl3Mx8FfpgAAANMAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjj8LwjAQxb9KGiGjKYIdmhgQ7eCiDl1KcUib2BaaPySRKvjhbSrocL977+44Hk2Ol0NZXQsgQE2T4lyeygpwAPdolW0JGgOB7DdvAKwRJ++5bpDdGJ1yYdqHkjqApxq1z6cd7EOwOca+7aXifm2s1PPubpziYbauw5NxwjrTSu8H3akRb9I0w4oPGsaXjRGv2G2EiwgMNYTiKCLdQrvwe4z/QdgHUEsBAhQDFAAAAAgAmq0yXczHwV+mAAAA0wAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAANUAAAAAAA==",
      "\n[AA<|AA<]\n",
      "REJECT:xml_dtd_rejected",
    ],
    [
      "ent_attr.docx",
      "UEsDBBQAAAAIAJqtMl23NtZvlQAAALkAAAARAAAAd29yZC9kb2N1bWVudC54bWw1zj0PwiAQBuC/QhkcpXFwQMqiHVzUgZg0xgHL9SMpHwEM+u8tJC7P3ZvLXY5Vp+tRdLcWKfRgVXsRZ9EhQPiO+ZOzRJXt3xpMRB+9mEBTg6cYHSUk9BNoGbbWgVlng/VaxjX6kSTrlfO2hxBmM+qF7Op6T7ScDc4nX1Z9kWzwBg4lu4zPRB4ZySXri66YV0rzf4f/AFBLAQIUAxQAAAAIAJqtMl23NtZvlQAAALkAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAADEAAAAAAA=",
      "\nt\n",
      "REJECT:xml_dtd_rejected",
    ],
    [
      "ent_external.docx",
      "UEsDBBQAAAAIAJqtMl2uzDRdowAAAM0AAAARAAAAd29yZC9kb2N1bWVudC54bWxFzrkOwjAMBuBXSTMw4oqBoYQs0IGBQ2qWCjGEJj2k5lASlPbtacrA8tmWf1km2fl+YvWjRAI9SVbe2IXVSKKqrlh5RbgdRlkAgAwNWO59FJi+KImFMM1HSR3QpEbti3jEfQh2ifqml4r7rbFSL7vWOMXDMroOonHCOtNI7wfdqRF2eb4HxQeN08m3EXOqNuESgU4beZgJpDbpVu3qLw7/V+gXUEsBAhQDFAAAAAgAmq0yXa7MNF2jAAAAzQAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAANIAAAAAAA==",
      "\n",
      "REJECT:xml_dtd_rejected",
    ],
    [
      "ent_param.docx",
      "UEsDBBQAAAAIAJqtMl0q8cj1lgAAAMIAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzj0LwjAQBuC/cg24esXBIcQsmsFFHbIUcahNbAvNh0mk9d/bVNDlebkPjmPF4byX1UWAgisrxEkeZQUr8ECehP8aGogg/MbZSJVrXkbbBJMZbKTjjnQpeYoYm06bOq6d13aePVwwdZrL0OLogvLBNTrG3rZmwE1ZbtHUvSX55N2pd06fCZnEJ4Y5smHRL35X8f8G/wBQSwECFAMUAAAACACarTJdKvHI9ZYAAADCAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAxQAAAAAA",
      "\nx\n",
      "REJECT:xml_dtd_rejected",
    ],
    [
      "ent_undefined_with_dtd.docx",
      "UEsDBBQAAAAIAJqtMl1w6JOPlAAAALYAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzj0PwiAQBuC/QhkcvcbBoSKLMrioA0tjHGrBtknhCGD68estdXB57t7c5XIsO99OsrwLosiDZeIqL7IkmlBB+ZOzoVBYf4y2kYymt6EYjrSN0RUAoW61qcIWnbbL7I3eVHGJvoEBvXIeax1CZxvTwy7P92CqztJ08oVqStUlfCLycTPPh4lB6pN+1a3+9uH/C/8CUEsBAhQDFAAAAAgAmq0yXXDok4+UAAAAtgAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAAMMAAAAAAA==",
      "\n",
      "REJECT:xml_dtd_rejected",
    ],
    [
      "ent_external_dtd.docx",
      "UEsDBBQAAAAIAJqtMl2nF4r1jwAAALMAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzj0PgjAQBuC/UhkcOeLgUJFFGI0msDBiW4GEfuRa08Kvl9bB5bl7c5fLlYf6cev6Z0M4afu2a+4kCzl3PKtKT7lmHymUI0EuylJ/zSbnDAWwbBJysLk2Qu2zt0Y5uD3iCF4jN6iZsHZWo1zgVBRnkMOs0smX5musJoIRV4Xjtl3WEmIfxaRJ/vbh/0v1BVBLAQIUAxQAAAAIAJqtMl2nF4r1jwAAALMAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAAC+AAAAAAA=",
      "\n",
      "REJECT:xml_dtd_rejected",
    ],
    [
      "ent_markup.docx",
      "UEsDBBQAAAAIAJqtMl1yHUWxlwAAAMIAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjj8PgjAQxb9K6eDoGQcHrF2UwUUdWIhxQHoCCb021xr020thcPm9+5f3TmWn67GsboUw4q6y4lKey0qgkGrMo+6JkBWkUuqHnmbGNW+LFMXHDhTy8SC7GH0OEJoObR3WziNNu5djW8ep5RZGx8azazCEnlo7wHaz2YGte5LJ8unMN6lPYD0Hr3C/xCbyTD9zOYb/I/oHUEsBAhQDFAAAAAgAmq0yXXIdRbGXAAAAwgAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAAMYAAAAAAA==",
      "\ninner\n",
      "REJECT:xml_dtd_rejected",
    ],
    [
      "ent_recursive.docx",
      "UEsDBBQAAAAIAJqtMl3QTNImkQAAALUAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzr0OwiAQAOBXoQyOXuPggMiiHVzUgaUxDgjYNik/AQz69kIdXL67y13ujjbHy4H31w4pdKNNd+Yn3iOB8ErsMLszmoly8mW0TehtZhtJ3uMxJU8Aohy1EXHtvLal93TBiFTKMEB2QfngpI5xsoOZYdO2WzBisriufDj1qdFXQiWxcpBCTaph0S/+huH/CPsCUEsBAhQDFAAAAAgAmq0yXdBM0iaRAAAAtQAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAAMAAAAAAAA==",
      "\n",
      "REJECT:xml_dtd_rejected",
    ],
    [
      "ent_billion.docx",
      "UEsDBBQAAAAIAJqtMl1C/Kx6pAAAABQBAAARAAAAd29yZC9kb2N1bWVudC54bWx9jj0PgjAQhv9K6cDoEQcHqF2UwUUdWIhxKG0FEvqRtgb991JM0InLm+e+3lyOJMfLoaqvJRLoRpLyXJ2qGjGE2RKYLvMG4ZQVK/rz8snbFCvC9E7JmAvDn0rqgF5q0D4f97gLweYAnndSMb8xVupp9zBOsTC1roXROGGd4dL7XrdqgG2W7UCxXuN4sjHiHbONcBGBprwgEItIN9PO/Jrh9wj9AFBLAQIUAxQAAAAIAJqtMl1C/Kx6pAAAABQBAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAADTAAAAAAA=",
      "\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
      "REJECT:xml_dtd_rejected",
    ],
    [
      "g_badutf8name.docx",
      "UEsDBBQAAAAIADSuMl1YuGw4aQAAAIUAAAARAAAAd29yZC9kb2N1bWVudC54bWw1zUsOwjAMBNCroB4AVyxYRCF3CUloK9Uf2UaB29NUYvM0o1lM7KFyeWMjv3xwJwv9Ma3uEgCsrA2zXVkaHduLFbMfVRforFWUSzPbaMEdbvN8B8wbTSn2IAMdeHpy/UYYaaincvo/Tj9QSwMEFAAACAgANK4yXYMW3IwDAAAAAQAAAA0AAAB3b3JkL//+enouYmluqwAAUEsBAhQDFAAAAAgANK4yXVi4bDhpAAAAhQAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsBAhQDFAAACAgANK4yXYMW3IwDAAAAAQAAAA0AAAAAAAAAAAAAAIABmAAAAHdvcmQv//56ei5iaW5QSwUGAAAAAAIAAgB6AAAAxgAAAAAA",
      {
        err: "UnicodeDecodeError",
        msg: "'utf-8' codec can't decode byte 0xff in position 5: invalid start byte",
      },
      "ERR:UnicodeDecodeError",
    ],
    [
      "g_cp437name.docx",
      "UEsDBBQAAAAIADSuMl1YuGw4aQAAAIUAAAARAAAAd29yZC9kb2N1bWVudC54bWw1zUsOwjAMBNCroB4AVyxYRCF3CUloK9Uf2UaB29NUYvM0o1lM7KFyeWMjv3xwJwv9Ma3uEgCsrA2zXVkaHduLFbMfVRforFWUSzPbaMEdbvN8B8wbTSn2IAMdeHpy/UYYaaincvo/Tj9QSwMEFAAAAAgANK4yXSK4AJlgAAAAeAAAAA4AAAB3b3JkL2hkcoDhLnhtbB3NQQqAIBAF0KtEB2iiRQsx7yJqGjQ6zAh2/NTN+3z+4uumkuflwzeLateaaiUFIC4FtLIVCrlvd2G0tVeO0Ap74uKCyJMjvnDs+wlon7wa3RQNeFBN0jBiyFOa9kPzA1BLAQIUAxQAAAAIADSuMl1YuGw4aQAAAIUAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLAQIUAxQAAAAIADSuMl0iuACZYAAAAHgAAAAOAAAAAAAAAAAAAACAAZgAAAB3b3JkL2hkcoDhLnhtbFBLBQYAAAAAAgACAHsAAAAkAQAAAAA=",
      "\nbody\n",
      "\nbody\n",
    ],
    [
      "g_dupheader.docx",
      "UEsDBBQAAAAIADSuMl1YuGw4aQAAAIUAAAARAAAAd29yZC9kb2N1bWVudC54bWw1zUsOwjAMBNCroB4AVyxYRCF3CUloK9Uf2UaB29NUYvM0o1lM7KFyeWMjv3xwJwv9Ma3uEgCsrA2zXVkaHduLFbMfVRforFWUSzPbaMEdbvN8B8wbTSn2IAMdeHpy/UYYaaincvo/Tj9QSwMEFAAAAAgANK4yXeIHijBmAAAAfgAAABAAAAB3b3JkL2hlYWRlcjEueG1sHc2xDoUgDIXhVzHuWnMHB4LMvgZRFBILTduE+/iCy5f8OcOx1cSThz8+WUzdxqhKBkCOGNDLXCjktl2F0WtLvqEWPonLEURSvvGB37KsgD7l0dlqqMMddft0JRa10KPLn/TZbt0LUEsDBBQAAAAIADSuMl3SglDlZwAAAH8AAAAQAAAAd29yZC9oZWFkZXIxLnhtbB3NywrDIBCF4Vcp2bcTuuhCjOu8hqiNgcyFGcE+fjWbD37O4vjuatbHDy8y17eltiYOwFItGO3FUmhsX1aMbaQe0FmzKKdidtKBF7zX9QMYT1qC704mOmlhf1pJTNnDrKneyu34DX9QSwECFAMUAAAACAA0rjJdWLhsOGkAAACFAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwECFAMUAAAACAA0rjJd4geKMGYAAAB+AAAAEAAAAAAAAAAAAAAAgAGYAAAAd29yZC9oZWFkZXIxLnhtbFBLAQIUAxQAAAAIADSuMl3SglDlZwAAAH8AAAAQAAAAAAAAAAAAAACAASwBAAB3b3JkL2hlYWRlcjEueG1sUEsFBgAAAAADAAMAuwAAAMEBAAAAAA==",
      "\nbody\n\nH-second\n\nH-second\n",
      "REJECT:duplicate_archive_member",
    ],
    [
      "g_sharedheader.docx",
      "UEsDBBQAAAAIADSuMl1YuGw4aQAAAIUAAAARAAAAd29yZC9kb2N1bWVudC54bWw1zUsOwjAMBNCroB4AVyxYRCF3CUloK9Uf2UaB29NUYvM0o1lM7KFyeWMjv3xwJwv9Ma3uEgCsrA2zXVkaHduLFbMfVRforFWUSzPbaMEdbvN8B8wbTSn2IAMdeHpy/UYYaaincvo/Tj9QSwMEFAAAAAgANK4yXd9wro9jAAAAeQAAABAAAAB3b3JkL2hlYWRlcjEueG1sHc0xDoAgEATArxgf4BELC4LU9r6AKIoJB5c7Eny+YDObzRZrqg4nDy/GJLquYyiFNIAcwaOTKZNPbbsyoyut8g0180mcDy/ypBsjzEotgO5JozVVU4c7xW67gZ5d/qXf9mg/UEsBAhQDFAAAAAgANK4yXVi4bDhpAAAAhQAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsBAhQDFAAAAAgANK4yXd9wro9jAAAAeQAAABAAAAAAAAAAAAAAAIABmAAAAHdvcmQvaGVhZGVyMS54bWxQSwECFAMUAAAACAA0rjJd33Cuj2MAAAB5AAAAEAAAAAAAAAAAAAAAgAGYAAAAd29yZC9oZWFkZXIxLnhtbFBLBQYAAAAAAwADALsAAAApAQAAAAA=",
      "\nbody\n\nHS\n\nHS\n",
      "REJECT:duplicate_archive_member",
    ],
    [
      "g_encrypted.docx",
      "UEsDBBQAAQAIADSuMl0uH1/9ZwAAAIQAAAARAAAAd29yZC9kb2N1bWVudC54bWw1zUsKwzAMBNCrlBygCl10YVzfxThqEog+SCru8RsHunnMMIvJPS3SPoQcty8d7Km/pi1CE4C3Dan6XRT53N5iVOOstkIXW9SkofvOKx3wmOcnUN15KrknHdggCnLLMMLQLvXy/1t+UEsBAhQDFAABAAgANK4yXS4fX/1nAAAAhAAAABEAAAAAAAAAAAAAAIABAAAAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAABAAEAPwAAAJYAAAAAAA==",
      {
        err: "RuntimeError",
        msg: "File 'word/document.xml' is encrypted, password required for extraction",
      },
      "REJECT:encrypted_archive",
    ],
    [
      "g_corruptdeflate.docx",
      "UEsDBBQAAAAIADSuMl1F9MEcdAAAADkCAAARAAAAd29yZC9kb2N1bWVudC54bWz///////8QBeCrBA/QkS66CGnuEmKqgvPDZCQ9fo3QQwhuPt7wlm9C8xPnHQuZ++JG1bf3sJiJB6h5KZjqg6XQ0X1YMdlx6gyNdRLlXGpdacYNnuP4AkwrDTE0Lx3tWMysuos5LO6OF4oB+npdPZXT/7PEH1BLAQIUAxQAAAAIADSuMl1F9MEcdAAAADkCAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAACjAAAAAAA=",
      { err: "error", msg: "Error -3 while decompressing data: invalid block type" },
      "ERR:error",
    ],
    [
      "g_method1.docx",
      "UEsDBBQAAAABADSuMl3PEP4GZgAAAIIAAAARAAAAd29yZC9kb2N1bWVudC54bWw1zUsKhDAQBNCriAewZRazCJncJcSMCvaH7pZ4/DHCbF5R1KJiCwuXEyv5cOFBFtpn3NwlAFjZKmabWCrd25cVs99VV2isiyiXarbTige85vkNmHcaU2xBOtrxhBF6dPVRHv+v6QdQSwECFAMUAAAAAQA0rjJdzxD+BmYAAACCAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAlQAAAAAA",
      { err: "NotImplementedError", msg: "That compression method is not supported" },
      "REJECT:invalid_archive",
    ],
    [
      "g_method99.docx",
      "UEsDBBQAAABjADSuMl3PEP4GZgAAAIIAAAARAAAAd29yZC9kb2N1bWVudC54bWw1zUsKhDAQBNCriAewZRazCJncJcSMCvaH7pZ4/DHCbF5R1KJiCwuXEyv5cOFBFtpn3NwlAFjZKmabWCrd25cVs99VV2isiyiXarbTige85vkNmHcaU2xBOtrxhBF6dPVRHv+v6QdQSwECFAMUAAAAYwA0rjJdzxD+BmYAAACCAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAlQAAAAAA",
      { err: "NotImplementedError", msg: "That compression method is not supported" },
      "REJECT:invalid_archive",
    ],
    [
      "g_badlocalmagic.docx",
      "WFhYWBQAAAAIADSuMl3PEP4GZgAAAIIAAAARAAAAd29yZC9kb2N1bWVudC54bWw1zUsKhDAQBNCriAewZRazCJncJcSMCvaH7pZ4/DHCbF5R1KJiCwuXEyv5cOFBFtpn3NwlAFjZKmabWCrd25cVs99VV2isiyiXarbTige85vkNmHcaU2xBOtrxhBF6dPVRHv+v6QdQSwECFAMUAAAACAA0rjJdzxD+BmYAAACCAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAlQAAAAAA",
      { err: "BadZipFile", msg: "Bad magic number for file header" },
      "REJECT:invalid_archive",
    ],
    [
      "g_badcdmagic.docx",
      "UEsDBBQAAAAIADSuMl3PEP4GZgAAAIIAAAARAAAAd29yZC9kb2N1bWVudC54bWw1zUsKhDAQBNCriAewZRazCJncJcSMCvaH7pZ4/DHCbF5R1KJiCwuXEyv5cOFBFtpn3NwlAFjZKmabWCrd25cVs99VV2isiyiXarbTige85vkNmHcaU2xBOtrxhBF6dPVRHv+v6QdYWFhYFAMUAAAACAA0rjJdzxD+BmYAAACCAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAAlQAAAAAA",
      { err: "BadZipFile", msg: "Bad magic number for central directory" },
      "REJECT:invalid_archive",
    ],
    [
      "g_notzip.docx",
      "aGVsbG8gdGhpcyBpcyBub3QgYSB6aXA=",
      { err: "BadZipFile", msg: "File is not a zip file" },
      "REJECT:format_mismatch",
    ],
    [
      "g_quotename_ok.docx",
      "UEsDBBQAAAAIADSuMl1YUDmJZwAAAIIAAAARAAAAd29yZC9kb2N1bWVudC54bWw1zUsOgzAMBNCrVBygRl10EYXcJQopIOEPtqv0+BCkbt5oNIuJLcxcvljJHz/cyUKbhtVdAoCVtWK2J0ula/uwYvar6gKNdRblUs02WnCH1zi+AfNGQ4otSEc7no4IPbp6K7f/13QCUEsDBBQAAAAIADSuMl3UHNEBBgAAAAQAAAANAAAAd29yZC9pdCdzLnhtbLNJ1LcDAFBLAQIUAxQAAAAIADSuMl1YUDmJZwAAAIIAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLAQIUAxQAAAAIADSuMl3UHNEBBgAAAAQAAAANAAAAAAAAAAAAAACAAZYAAAB3b3JkL2l0J3MueG1sUEsFBgAAAAACAAIAegAAAMcAAAAAAA==",
      "\nq\n",
      "\nq\n",
    ],
    [
      "err_z_localname.docx",
      "UEsDBBQAAAAIAEaqMl1E/9uyoQAAANwAAAARAAAAV09SRC9kb2N1bWVudC54bWxFjkEOwiAQRa9C2FuqC2Oa0u48gR4AYWybwAxh0NrbC3Xh5v1Mfv7L9OMnePGGxAuhlsemlQLQkltw0vJ+ux4uUnA26IwnBC03YDkO/do5sq8AmEURIHerlnPOsVOK7QzBcEMRsHRPSsHkcqZJrZRcTGSBufiDV6e2PatgFpRV+SC31YwVqSIPnqzxAk0AERYuJjv3qhaVaWfc+Rur/2PDF1BLAQIUAxQAAAAIAEaqMl1E/9uyoQAAANwAAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAADQAAAAAAA=",
      {
        err: "BadZipFile",
        msg: "File name in directory 'word/document.xml' and header b'WORD/document.xml' differ.",
      },
      null,
    ],
    [
      "err_z_trunc_deflate.docx",
      "UEsDBBQAAAAIAEaqMl2W64wIogAAACEDAAARAAAAd29yZC9kb2N1bWVudC54bWztkjsOwjAQRK9iuScOFAhF+XScAA5g7CWJFO9a9oaQ22OHggtQpnk7o5WmenX3dpN4QYgjYSOPRSkFoCE7Yt/I++16uEgRWaPVEyE0coUou7ZeKktmdoAs0gDGamnkwOwrpaIZwOlYkAdMvycFpznV0KuFgvWBDMSY9t2kTmV5Vk6PKPPkg+yar88IGdxymNFoBuFA7HnP/8q1ynZlho1+49dA9bO7/QBQSwECFAMUAAAACABGqjJdluuMCKIAAAAhAwAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAA1wAAAAAA",
      { err: "BadZipFile", msg: "Bad CRC-32 for file 'word/document.xml'" },
      null,
    ],
    ["err_z_zero.docx", "", { err: "BadZipFile", msg: "File is not a zip file" }, null],
    [
      "err_e_badextra.docx",
      "UEsDBBQAAAAIAAAAIQAcOePYgQAAALAAAAARAAYAd29yZC9kb2N1bWVudC54bWyZmTIAYWJFzjEOwyAMBdCrIA4Q0w4dECFnIUATpICRoSW9fSEdujzr68uW1XLGg709lYBp5rdJ8EWrJh3aV/Spsl6nItvM91qzBCh299GUCbNPvXsiRVN7pA0aksuE1pcS0hYPuAvxgGhC4uPkiu4zZh7QoOrVOObPSkbBiEO6zJe/Ffi/o79QSwECFAMUAAAACAAAACEAHDnj2IEAAACwAAAAEQAGAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWyZmTIAYWJQSwUGAAAAAAEAAQBFAAAAtgAAAAAA",
      { err: "BadZipFile", msg: "Corrupt extra field 9999 (size=50)" },
      null,
    ],
    [
      "err_e_cdsize_big.docx",
      "UEsDBBQAAAAIACCsMl0fx8FngAAAAK0AAAARAAAAd29yZC9kb2N1bWVudC54bWxFzsEOwiAMBuBXWXiAdXrwQBh7FgTcSAYlLQ716YV58PK1zd80Vcsr7sPhiQOmWVzGSSxaVenQPqNPZWhxYllnsZWSJQDbzUfDI2afWvZAiqa0kVaoSC4TWs8c0hp3uE7TDaIJSfSTd3TvXnOHOkVbx+HjFfS+S6f59LcP/1/0F1BLAwQUAAAACAAgrDJduJyrhhIAAAAQAAAAEAAAAHdvcmQvaGVhZGVyMS54bWyzUXTxdw6JDHBVqLCzSdS3AwBQSwECFAMUAAAACAAgrDJdH8fBZ4AAAACtAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwECFAMUAAAACAAgrDJduJyrhhIAAAAQAAAAEAAAAAAAAAAAAAAAgAGvAAAAd29yZC9oZWFkZXIxLnhtbFBLBQYAAAAAAgACAIcAAADvAAAAAAA=",
      { err: "BadZipFile", msg: "Bad magic number for central directory" },
      null,
    ],
    [
      "err_e_cdsize_small.docx",
      "UEsDBBQAAAAIACCsMl0fx8FngAAAAK0AAAARAAAAd29yZC9kb2N1bWVudC54bWxFzsEOwiAMBuBXWXiAdXrwQBh7FgTcSAYlLQ716YV58PK1zd80Vcsr7sPhiQOmWVzGSSxaVenQPqNPZWhxYllnsZWSJQDbzUfDI2afWvZAiqa0kVaoSC4TWs8c0hp3uE7TDaIJSfSTd3TvXnOHOkVbx+HjFfS+S6f59LcP/1/0F1BLAwQUAAAACAAgrDJduJyrhhIAAAAQAAAAEAAAAHdvcmQvaGVhZGVyMS54bWyzUXTxdw6JDHBVqLCzSdS3AwBQSwECFAMUAAAACAAgrDJdH8fBZ4AAAACtAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwECFAMUAAAACAAgrDJduJyrhhIAAAAQAAAAEAAAAAAAAAAAAAAAgAGvAAAAd29yZC9oZWFkZXIxLnhtbFBLBQYAAAAAAgACAHMAAADvAAAAAAA=",
      { err: "BadZipFile", msg: "Bad magic number for central directory" },
      null,
    ],
    [
      "err_e_flag5.docx",
      "UEsDBBQAAAAIACCsMl1MVSF3fgAAAKsAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzjEOwyAMBdCrRBwgph06oISchQIhSICRoaG9fSEdujzb+pblZXvHMJ2Wise0stvM2SaXJgzqV7SpTj1ORbSVHbVmAVD0YaMqM2aberYjRVX7SA4aksmE2pbik4sB7pw/ICqf2Dj5RPMZNQ9oUOUelFtgdEO6zJe/bfh/Ir9QSwECFAMUACAACAAgrDJdTFUhd34AAACrAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAArQAAAAAA",
      { err: "NotImplementedError", msg: "compressed patched data (flag bit 5)" },
      null,
    ],
    [
      "err_e_flag6.docx",
      "UEsDBBQAAAAIACCsMl1MVSF3fgAAAKsAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzjEOwyAMBdCrRBwgph06oISchQIhSICRoaG9fSEdujzb+pblZXvHMJ2Wise0stvM2SaXJgzqV7SpTj1ORbSVHbVmAVD0YaMqM2aberYjRVX7SA4aksmE2pbik4sB7pw/ICqf2Dj5RPMZNQ9oUOUelFtgdEO6zJe/bfh/Ir9QSwECFAMUAEAACAAgrDJdTFUhd34AAACrAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAArQAAAAAA",
      { err: "NotImplementedError", msg: "strong encryption (flag bit 6)" },
      null,
    ],
    [
      "err_e_overlap.docx",
      "UEsDBBQAAAAIACCsMl2+QBmeiAAAAOcBAAARAAAAd29yZC9kb2N1bWVudC54bWztkUEOAiEMRa9COMAUXbggDHMWBJwhAUoKOnp7YVy4d+3mvTQ/aZNftTxTZA9PNWCe+WkSfNFqlw7tPfncWI9zlfvMt9aKBKh288nUCYvPPbshJdP6SCvsSK4QWl9ryGuKcBbiAsmEzMfKK7rXcBmggaaxX46msL9/s4LR4iAdLAc/TcP3i/oNUEsDBBQAAAAIACCsMl2cGG/jfgAAAKgAAAAQAAAAd29yZC9oZWFkZXIxLnhtbEXOMQ7DIAwF0KtEHCCmHTogQtZeIwWaIAWMbFLa2xfSocv7sr5lWc/vuA8vTxwwTeIySjEbXZVDe0SfytDqxKpOYislKwC2m48Lj5h9at0TKS6ljbRCRXKZ0HrmkNa4w1XKG8QlJNFPPtB9euYOdYq5a+jRpdN8+luF/xvmC1BLAQIUAxQAAAAIACCsMl2+QBmesAAAAOcBAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLAQIUAxQAAAAIACCsMl2cGG/jfgAAAKgAAAAQAAAAAAAAAAAAAACAAbcAAAB3b3JkL2hlYWRlcjEueG1sUEsFBgAAAAACAAIAfQAAAGMBAAAAAA==",
      { err: "BadZipFile", msg: "Overlapped entries: 'word/document.xml' (possible zip bomb)" },
      null,
    ],
    [
      "err_e_stored_small.docx",
      "UEsDBBQAAAAAACCsMl1hSAd3sQAAALEAAAARAAAAd29yZC9kb2N1bWVudC54bWw8P3htbCB2ZXJzaW9uPSIxLjAiPz48dzpkb2N1bWVudCB4bWxuczp3PSJodHRwOi8vc2NoZW1hcy5vcGVueG1sZm9ybWF0cy5vcmcvd29yZHByb2Nlc3NpbmdtbC8yMDA2L21haW4iPjx3OmJvZHk+PHc6cD48dzpyPjx3OnQ+c3RvcmVkIGxpZTwvdzp0PjwvdzpyPjwvdzpwPjwvdzpib2R5Pjwvdzpkb2N1bWVudD5QSwECFAMUAAAAAAAgrDJdYUgHd7EAAACsAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAA4AAAAAAA",
      { err: "BadZipFile", msg: "Bad CRC-32 for file 'word/document.xml'" },
      null,
    ],
    [
      "err_e_ver64.docx",
      "UEsDBBQAAAAIACCsMl0LcxFzfgAAAKoAAAARAAAAd29yZC9kb2N1bWVudC54bWxFjkEOwyAMBL8S8YCY9tADIuQtFGiCFGNkaGl/X0gPvYx3tZa9en3jMb0Cl0hpEZdZitXopjy5J4ZUpx6notoi9lqzAihuD2jLTDmknj2I0dZueYNG7DOTC6XEtOEBVylvgDYmMU7eyX/GzAM8UE1/rGGIQT6ZT/6W4V/EfAFQSwECFANAAAAACAAgrDJdC3MRc34AAACqAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAArQAAAAAA",
      { err: "NotImplementedError", msg: "zip file version 6.4" },
      null,
    ],
    [
      "e_stored_big.docx",
      "UEsDBBQAAAAAACCsMl1hSAd3sQAAALEAAAARAAAAd29yZC9kb2N1bWVudC54bWw8P3htbCB2ZXJzaW9uPSIxLjAiPz48dzpkb2N1bWVudCB4bWxuczp3PSJodHRwOi8vc2NoZW1hcy5vcGVueG1sZm9ybWF0cy5vcmcvd29yZHByb2Nlc3NpbmdtbC8yMDA2L21haW4iPjx3OmJvZHk+PHc6cD48dzpyPjx3OnQ+c3RvcmVkIGxpZTwvdzp0PjwvdzpyPjwvdzpwPjwvdzpib2R5Pjwvdzpkb2N1bWVudD5QSwECFAMUAAAAAAAgrDJdYUgHd7EAAADjAAAAEQAAAAAAAAAAAAAAgAEAAAAAd29yZC9kb2N1bWVudC54bWxQSwUGAAAAAAEAAQA/AAAA4AAAAAAA",
      "\nstored lie\n",
      "\nstored lie\n",
    ],
    [
      "e_deflate_short.docx",
      "UEsDBBQAAAAIACCsMl29VbXJjAAAAPEBAAARAAAAd29yZC9kb2N1bWVudC54bWztkUEOwjAMBL8S5QF14cChStu3hCQ0lZo4sg2F35OUAw/gymW81kp72DXzM23qEYhXzKM+db2eJ7MPHt09hSyq2pmHfdRRpAwA7GJIljssIVfvhpSs1JcW2JF8IXSBec1L2uDc9xdIds26RV7Rv9otDdQgE0ckUd6KVX/5kzTQ+mykg+Xgp3P47jm9AVBLAQIUAxQAAAAIACCsMl29VbXJjAAAAFUCAAARAAAAAAAAAAAAAACAAQAAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAQABAD8AAAC7AAAAAAA=",
      "\nshort data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data \n",
      "\nshort data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data short data \n",
    ],
  ];
  for (const [file, base64, raw, bounded] of cases) {
    it(`docx.readText === Python: ${file}`, async () => {
      const path = fixture(file, base64);
      let actual: Outcome;
      try {
        actual = await readDocx(path);
      } catch (e) {
        actual = { err: (e as Error).name, msg: (e as Error).message };
      }
      expect(actual).toEqual(raw);
      if (bounded === null) return;
      let actualBounded: string;
      try {
        actualBounded = (await readTextBounded(path)).text;
      } catch (e) {
        actualBounded =
          e instanceof BoundedReadError ? `REJECT:${e.code}` : `ERR:${(e as Error).name}`;
      }
      expect(actualBounded).toBe(bounded);
    });
  }
});

describe("csvReader — csv.Sniffer / _csv 파서", () => {
  const cases: Array<[text: string, python: Array<Record<string, string>>]> = [
    [
      "a, b\n1, 2\n3, 4\n",
      [
        { a: "1", b: "2" },
        { a: "3", b: "4" },
      ],
    ],
    [
      "name, phone, memo\nhong, 010-1234-5678, x\nkim, 010-0000-0000, y\n",
      [
        { name: "hong", phone: "010-1234-5678", memo: "x" },
        { name: "kim", phone: "010-0000-0000", memo: "y" },
      ],
    ],
    [
      "a,b\n1\u00002,3\n4,5\n",
      [
        { a: "1\u00002", b: "3" },
        { a: "4", b: "5" },
      ],
    ],
    ['a,b\n"1\u0000",2\n', [{ a: "1\u0000", b: "2" }]],
    ["a,b\n1,2\n", [{ a: "1", b: "2" }]],
  ];
  for (const [text, python] of cases) {
    it(`readRecords === Python: ${JSON.stringify(text)}`, () => {
      expect(readRecordsFromText(text)).toEqual(python);
    });
  }

  it("필드 한도 131072 — 정확히 한도는 통과, 1자 초과는 csv.Error", () => {
    const ok = readRecordsFromText(`a,b\n"${"x".repeat(131072)}",2\n`);
    expect(String(ok[0]?.a).length).toBe(131072);
    expect(() => readRecordsFromText(`a,b\n"${"x".repeat(131073)}",2\n`)).toThrow(CsvError);
    expect(() => readRecordsFromText(`a,b\n"${"x".repeat(131073)}",2\n`)).toThrow(
      "field larger than field limit (131072)",
    );
  });
});

describe("textNormalizer — Python \\d / \\s 의미론 (offset map 포함)", () => {
  const cases: Array<[text: string, python: [string, number[]]]> = [
    [
      "계좌 １２３ ４５６ - ７８ - ９０１２３\n",
      [
        "계좌 １２３４５６-７８-９０１２３\n",
        [0, 1, 2, 3, 4, 5, 7, 8, 9, 11, 13, 14, 16, 18, 19, 20, 21, 22, 23],
      ],
    ],
    ["٣٤٥ - ٦٧ - ٨٩٠١٢", ["٣٤٥-٦٧-٨٩٠١٢", [0, 1, 2, 4, 6, 7, 9, 11, 12, 13, 14, 15]]],
    ["123\u001c- 45 - 678", ["123\u001c-45-678", [0, 1, 2, 3, 4, 6, 7, 9, 11, 12, 13]]],
    ["123﻿- 45 - 678", ["123﻿- 45-678", [0, 1, 2, 3, 4, 5, 6, 7, 9, 11, 12, 13]]],
    ["123- 45 - 678", ["123-45-678", [0, 1, 2, 3, 4, 6, 7, 9, 11, 12, 13]]],
    ["123　-　45 - 678", ["123　-　45-678", [0, 1, 2, 3, 4, 5, 6, 7, 9, 11, 12, 13]]],
    ["49 9 - 8 7- 0 3 8", ["499-87-038", [0, 1, 3, 5, 7, 9, 10, 12, 14, 16]]],
    [
      "9 5 1 2 3 0 - 1 8 5 0 4 3 1",
      ["951230-1850431", [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26]],
    ],
    [
      "880101-\n1234568 홍길\n동",
      [
        "880101- 1234568 홍길동",
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19],
      ],
    ],
  ];
  for (const [text, python] of cases) {
    it(`normalizeForDetection === Python: ${JSON.stringify(text)}`, () => {
      expect(normalizeForDetection(text)).toEqual(python);
    });
  }
});

describe("dispatcher — os.path.splitext 규칙", () => {
  const cases: Array<[path: string, pythonExt: string]> = [
    ["a.csv", ".csv"],
    ["A.CSV", ".csv"],
    [".csv", ""],
    ["..csv", ""],
    ["dir/.csv", ""],
    ["dir/..csv", ""],
    ["dir/.hidden.csv", ".csv"],
    ["dir.d/file", ""],
    ["dir.csv/noext", ""],
    ["a.", "."],
    ["a.tar.csv", ".csv"],
    ["t.csv ", ".csv "],
    ["noext", ""],
    ["", ""],
    ["/", ""],
    ["a/b.c/", ""],
    ["..a.b", ".b"],
    ["x/.docx", ""],
  ];
  for (const [path, pythonExt] of cases) {
    it(`extensionOf(${JSON.stringify(path)}) === ${JSON.stringify(pythonExt)}`, () => {
      expect(extensionOf(path)).toBe(pythonExt);
    });
  }

  it("숨김 파일 .csv 는 표 형식으로 라우팅하지 않는다 (Python read_records == [])", async () => {
    const path = fixture(".csv", Buffer.from("a,b\n1,2\n").toString("base64"));
    expect(await dispatchReadRecords(path)).toEqual([]);
  });
});

describe("io/index 공개 API", () => {
  it("remapOffsets 를 export 한다 (Python text_normalizer.remap_offsets)", () => {
    expect(typeof ioIndex.remapOffsets).toBe("function");
  });
});
