#!/usr/bin/env python3
"""Python 사전 모듈 → TypeScript 데이터 모듈 자동 변환.

실행: python3 tools/convert-dicts.py [--check]
입력: src/python/ko_pii/dictionaries/*.py (모듈 레벨 데이터 상수)
출력: src/ts/src/dictionaries/generated/<name>.ts + generated/index.ts

Python 사전을 진실 원천으로 유지해 수작업 전사 오류를 차단한다. 모듈 레벨의
frozenset/set/dict/tuple/str 상수만 변환하고 함수·클래스·비공개 이름은 건너뛴다.
생성물은 커밋 대상이며, 재생성 시 diff 가 곧 데이터 변경 리뷰가 된다.

--check: 재생성 없이 커밋된 생성물이 원본 사전과 동기화되어 있는지 검증한다.
(CI 와 tests/unit/test_cross_language_sync.py 가 동일 로직을 사용한다.)
"""
from __future__ import annotations

import json
import importlib
import sys
import types as pytypes
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src" / "python"))

from ko_pii.dictionaries import (  # noqa: E402
    agencies,
    agency_abbrev,
    agency_titles,
    common_words,
    districts,
    field_labels,
    majors,
    surnames,
    titles,
    universities,
)

# 패키지 __init__ 이 동명 함수 legal_dongs 를 재노출해 서브모듈을 가리므로 importlib 로 가져온다.
legal_dongs = importlib.import_module("ko_pii.dictionaries.legal_dongs")

MODULES = [
    agencies,
    agency_abbrev,
    agency_titles,
    common_words,
    districts,
    field_labels,
    legal_dongs,
    majors,
    surnames,
    titles,
    universities,
]

OUT = ROOT / "src" / "ts" / "src" / "dictionaries" / "generated"

# 모듈 상수가 아니라 번들 리소스에서 로드되는 데이터 — {모듈: {TS 상수명: 로더}}.
# npm 배포본(dist)은 Python 패키지 트리를 읽을 수 없으므로 생성물에 직접 싣는다.
RESOURCE_EXPORTS = {
    legal_dongs: {"LEGAL_DONGS": legal_dongs.legal_dongs},
}

HEADER = (
    "// GENERATED by tools/convert-dicts.py — 수동 편집 금지.\n"
    "// 원본: src/python/ko_pii/dictionaries/{module}.py — 데이터 변경은 Python 쪽에서 한 뒤 재생성.\n\n"
)


def ts_ident(name: str) -> str | None:
    if not name.isidentifier() or name.startswith("_"):
        return None
    return name


def ts_type_annotation(value) -> str:
    if isinstance(value, (frozenset, set)):
        return "ReadonlySet<string>"
    if isinstance(value, (list, tuple)):
        return "readonly string[]"
    if isinstance(value, dict):
        if all(isinstance(v, str) for v in value.values()):
            return "Readonly<Record<string, string>>"
        return "Readonly<Record<string, readonly string[]>>"
    if isinstance(value, str):
        return "string"
    return "unknown"


def ts_literal(value, indent: str = "  ") -> str:
    if isinstance(value, (frozenset, set)):
        items = sorted(value)
        if not items:
            return "new Set<string>([])"
        body = ",\n".join(f"{indent}  {json.dumps(s, ensure_ascii=False)}" for s in items)
        return f"new Set<string>([\n{body},\n{indent}])"
    if isinstance(value, (list, tuple)):
        items = list(value)
        if not items:
            return "[]"
        body = ",\n".join(f"{indent}  {json.dumps(s, ensure_ascii=False)}" for s in items)
        return f"[\n{body},\n{indent}]"
    if isinstance(value, dict):
        if not value:
            return "{}"
        entries = []
        for k, v in value.items():
            if isinstance(v, str):
                vlit = json.dumps(v, ensure_ascii=False)
            elif isinstance(v, (frozenset, set)):
                # set 순회는 PYTHONHASHSEED 마다 달라지므로 정렬해 결정론 유지.
                vlit = "[" + ", ".join(json.dumps(s, ensure_ascii=False) for s in sorted(v)) + "]"
            else:
                vlit = "[" + ", ".join(json.dumps(s, ensure_ascii=False) for s in v) + "]"
            entries.append(f"{indent}  {json.dumps(k, ensure_ascii=False)}: {vlit},")
        return "{\n" + "\n".join(entries) + f"\n{indent}}}"
    return json.dumps(value, ensure_ascii=False)


def convert_module(module) -> tuple[str, list[str]]:
    lines = [HEADER.format(module=module.__name__.rsplit(".", 1)[-1])]
    exported = []
    skipped = []
    for name, value in sorted(vars(module).items()):
        ident = ts_ident(name)
        if ident is None:
            continue
        if isinstance(value, pytypes.ModuleType) or callable(value):
            if name != "__builtins__":
                skipped.append(name)
            continue
        if not isinstance(value, (frozenset, set, dict, list, tuple, str)):
            skipped.append(name)
            continue
        ann = ts_type_annotation(value)
        lit = ts_literal(value)
        lines.append(f"export const {ident}: {ann} = {lit};\n")
        exported.append(ident)
    for ident, loader in RESOURCE_EXPORTS.get(module, {}).items():
        value = loader()
        lines.append(f"export const {ident}: {ts_type_annotation(value)} = {ts_literal(value)};\n")
        exported.append(ident)
    if skipped:
        lines.append(f"// 건너뜀(데이터 아님): {', '.join(sorted(skipped))}\n")
    return "\n".join(lines), exported


def render_all() -> dict[str, str]:
    """모든 생성 파일의 기대 내용을 {파일명: 내용} 으로 반환."""
    files: dict[str, str] = {}
    index_lines = [
        "// GENERATED by tools/convert-dicts.py — 수동 편집 금지.\n\n",
    ]
    for module in MODULES:
        stem = module.__name__.rsplit(".", 1)[-1]
        content, exported = convert_module(module)
        files[f"{stem}.ts"] = content
        rel = f"./{stem}.js"
        for ident in exported:
            index_lines.append(f'export {{ {ident} }} from "{rel}";\n')
    files["index.ts"] = "".join(index_lines)
    return files


def check() -> list[str]:
    """커밋된 TS 생성물과 원본 사전의 드리프트 파일 목록을 반환."""
    drifts = []
    for name, expected in sorted(render_all().items()):
        path = OUT / name
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual != expected:
            drifts.append(name)
    return drifts


def main(argv: list[str]) -> int:
    if "--check" in argv:
        drifts = check()
        if drifts:
            print(
                "TS 사전 생성물 드리프트 — python3 tools/convert-dicts.py 로 재생성하세요:",
                file=sys.stderr,
            )
            for name in drifts:
                print(f"  {OUT / name}", file=sys.stderr)
            return 1
        print(f"ok: TS 사전 생성물 {len(render_all())}개 파일이 원본과 동기화됨")
        return 0

    OUT.mkdir(parents=True, exist_ok=True)
    files = render_all()
    for name, content in files.items():
        path = OUT / name
        path.write_text(content, encoding="utf-8")
        print(f"  {name}: {len(content):,} bytes")
    print(f"done. 모듈 {len(MODULES)}개, 파일 {len(files)}개 → {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
